### PR TITLE
fix(backend-github): prepend collection name

### LINKED ISSUE #1396: CollectionName not prepended to branch names in Editorial Workflow mode
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

I have two collections which contain pages with the same names with different content. With the Editorial Workflow enabled changing any of these pages effects the other collections equivalent page.

I think I've worked out what is happening, it looks like the generated branch names do not contain the `collectionName-` as it suggests it should in the documentation.

At first I thought this was the same issue as https://github.com/netlify/netlify-cms/issues/1164 but I actually think its different.

Looking at the code I think the problem is here: https://github.com/netlify/netlify-cms/blob/55a24a75c14fcef97b19f9c1fe6cc1579e0b59c2/src/backends/github/API.js#L325

It seem as just the `slug` is passed to the `generateBranchName` function and not `options.collectionName` as well. I might be wrong though.

So in my case instead of `cms/pages-consumer/color`, I get `cms/color`.

**- If the current behavior is a bug, please provide the steps to reproduce.**

- Create two collections with pages/files of the same name
- Make a change to a file in one collection and see the branch/PR created with the name `cms/[name of file]`
- Try changing the corresponding file in the other collection and you should see the changes you made in the previous step.

**- What is the expected behavior?**

Branches should be created with the `collectionName` prepended to the branch name allowing them to be different.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.8.4
Browser version: Chrome 66

Node.JS version: 9.8.0
Operating System: OS X

**- Please link or paste your `config.yml` below if applicable.**

### LINKED ISSUE #1933: Incorrect branch name with GitHub backend
**Describe the bug**
According to the [docs](https://www.netlifycms.org/docs/configuration-options/#publish-mode), if my backend is Github, the branch name created from the CMS should be of the form `cms/collectionName-slug`, however, when I push from the CMS, the branch name is of the form `cms/slug`. This creates issues when I am modifying multiple pages of the same name from different directories, for example, `a/intro/` and `b/intro/`.

**Applicable Versions:**

 - Netlify CMS version: 2.1.3
 - Git provider: GitHub

**CMS configuration**
```
backend:
  name: github
  repo: random/repo
  squash_merges: true

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  - name: a
    label: a
    folder: content/a
    slug: "{{slug}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: b
    label: b
    folder: content/integration-guides/b
    slug: "{{slug}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
```

### LINKED ISSUE #2620: Overwriting occurs in editor when adding the same slug post with multiple collections
**Describe the bug**
I use NetlifyCMS with GatsbyJS.
When I try to save a post that has an existing slug in one collection to another collection, the edit screen of the same slug post in the first collection is overwritten by the one added later.
This is a problem only on the CMS and there is no problem with the display of the website.

**To Reproduce**
1. Enable editorial_workflow
2. Add and publish a post in one collection where slug can be entered in field
3. Add the same slug post in another collection and save it in draft state
4. View the edit screen of the post added in 2

**Expected behavior**
The same slug post in different collections should be editable without overwriting one.

**Screenshots**
After 2:
This screen's URL is `/admin/#/collections/one-posts/entries/001`
スクリーンショット 2019-08-29 15 36 03

After 3:
This screen's URL is `/admin/#/collections/another-posts/entries/001`
スクリーンショット 2019-08-29 15 37 56

After 4:
This screen's URL is `/admin/#/collections/one-posts/entries/001`
スクリーンショット 2019-08-29 15 38 20

**Applicable Versions:**
- Netlify CMS version: 2.9.7
- GatsbyJS version: 2.13.50
- Git provider: GitHub
- OS: macOS Mojave 10.14
- Browser version: Chrome 75
- Node.JS version: 10.13.0

**CMS configuration**
```yaml
backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow

collections:
  - name: "one-posts"
    label: "One posts"
    folder: "src/pages/one-posts"
    create: true
    slug: '{{fields.slug}}'
    fields:
      - {
          label: 'Template type',
          name: 'type',
          widget: 'hidden',
          default: 'one-posts',
        }
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
        default: '001'
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: "another-posts"
    label: "Another posts"
    folder: "src/pages/another-posts"
    create: true
    slug: '{{fields.slug}}'
    fields:
      - {
          label: 'Template type',
          name: 'type',
          widget: 'hidden',
          default: 'another-posts',
        }
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
        default: '001'
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```

**Additional context**
If I publish the post I added later, the problem will be solved.
However, I would like to be able to edit either of them in draft state.
Is there any good solution?
Because I am not an English speaker, I apologize for the ugly translation.

### PR DESCRIPTION
**Pull request by barthc**
**Summary**
Closes #2620, closes #1933, closes #1396

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks @barthc! Since Erez has a PR open that touches the workflow a lot I'm going to defer to him for review.

**Comment by erezrokah** [comment]
I like the new approach, but instead of baking in backwards compatibility into several different API methods, how about doing one single migrate operation?

A possible place to do it is in `listUnpublishedBranches` - we already get all the `cms/` branches, we can get their metadata (or even use labels to mark the ones that have been migrated like suggested here: https://github.com/netlify/netlify-cms/issues/1669).

Then we can rename the existing branches and update any relevant metadata.
The plus side it will fix those issues for existing branches as well.

**Comment by barthc** [comment]
I was thinking with this approach(backwards compatible), we can drop searching for the old key sometime in the future.

Regarding migration, I believe we discussed something like so in another PR. One of the issues is that we can't delete or rename(maybe not sure) any metadata file inside the orphaned branch. So the best we can do is duplicate the metadata file with the new key name.

I also don't think we can rename branch via the api.

**Comment by erezrokah** [comment]
Good points @barthc, I'll have time to take a closer look once I'm done with https://github.com/netlify/netlify-cms/pull/2851

**Comment by erquhart** [comment]
Creating a new branch and deleting the old should do the trick.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erezrokah** [comment]
How about something like this: https://github.com/netlify/netlify-cms/commit/b37faa0a95b87d0a1b45ac026bdc09720802342f

I cleaned up some of the code for getting unpublished branches, but the relevant migration code is here: https://github.com/netlify/netlify-cms/commit/b37faa0a95b87d0a1b45ac026bdc09720802342f#diff-b4ba42c688a23ed9cec5139daec2c157R452

It needs some more testing (manual and automatic) and some code cleanup though.

File: packages/netlify-cms-backend-github/src/API.js [hunk 1]
```diff
@@ -459,14 +475,55 @@ export default class API {
...
+
   async listUnpublishedBranches() {
     console.log(
       '%c Checking for Unpublished entries',
       'line-height: 30px;text-align: center;font-weight: bold',
     );
-    const onlyBranchesWithOpenPRs = filterPromisesWith(({ ref }) =>
-      this.branchHasPR({ branchName: this.branchNameFromRef(ref), state: 'open' }),
-    );
+    const onlyBranchesWithOpenPRs = flowAsync([
```
Comment (barthc) [inline packages/netlify-cms-backend-github/src/API.js]: Used a new `flowAsync` utility function, which is cleaner.

Comment (erezrokah) [reply packages/netlify-cms-backend-github/src/API.js]: Please see here:
https://github.com/netlify/netlify-cms/commit/b37faa0a95b87d0a1b45ac026bdc09720802342f#diff-b4ba42c688a23ed9cec5139daec2c157R518

Instead of sending a `pull` API request per branch and since that API uses substring match, we can send a single request with `cms` as the matching pattern and filter the branches according to the result.

**Comment by erezrokah** [comment]
Just noticed you ported the migration code. Nice one :)
I do have a bug in my branch where I don't set the metadata current version when persisting metadata.
I'll try to go over your recent changes soon

File: packages/netlify-cms-backend-github/src/API.js [hunk 2]
```diff
@@ -225,6 +224,29 @@ export default class API {
     );
   }
 
+  deleteMetadata(key) {
```
Comment (erezrokah) [inline packages/netlify-cms-backend-github/src/API.js]: Nice!

File: packages/netlify-cms-backend-github/src/implementation.js [hunk 3]
```diff
@@ -387,8 +387,8 @@ export default class GitHub {
         const promises = [];
         branches.map(({ ref }) => {
           promises.push(
-            new Promise(resolve => {
-              const contentKey = ref.split('refs/heads/cms/').pop();
+            new Promise(async resolve => {
```
Comment (erezrokah) [inline packages/netlify-cms-backend-github/src/implementation.js]: Is the `async` required?

Comment (barthc) [reply packages/netlify-cms-backend-github/src/implementation.js]: Sorry I forgot to remove that.

**Comment by barthc** [comment]
> I do have a bug in my branch where I don't set the metadata current version when persisting metadata.

Yes I added that in.

**Comment by erezrokah** [comment]
Hey @barthc. I added some unit tests, re-recorded the e2e tests data and made some code changes, the most notable one is to hard code the migration code.
We still want the migration code to work, even if the implementation of the key/branch generation changes in the future.

I'm good with merging if you are.

**Comment by barthc** [comment]
@erezrokah  thanks for the changes. I think we forgot to handle one edge case. I will push up shortly.

**Comment by erezrokah** [comment]
Cool, I'm pushing a fix for the GraphQL `createBranch` too

File: packages/netlify-cms-core/src/actions/editorialWorkflow.js [hunk 4]
```diff
@@ -242,6 +243,12 @@ export function loadUnpublishedEntry(collection, slug) {
   return async (dispatch, getState) => {
     const state = getState();
     const backend = currentBackend(state.config);
+    const entriesLoaded = get(state.editorialWorkflow.toJS(), 'pages.ids', false);
+    //run possible unpublishedEntries migration
+    if (!entriesLoaded) {
+      const response = await backend.unpublishedEntries(state.collections).catch(() => false);
```
Comment (barthc) [inline packages/netlify-cms-core/src/actions/editorialWorkflow.js]: For published entry that have a draft entry, let's run the migration code first before loading the draft.

File: packages/netlify-cms-core/src/actions/editorialWorkflow.js [hunk 5]
```diff
@@ -294,8 +301,10 @@ export function loadUnpublishedEntry(collection, slug) {
 export function loadUnpublishedEntries(collections) {
   return (dispatch, getState) => {
     const state = getState();
-    if (state.config.get('publish_mode') !== EDITORIAL_WORKFLOW) return;
     const backend = currentBackend(state.config);
+    const entriesLoaded = get(state.editorialWorkflow.toJS(), 'pages.ids', false);
```
Comment (barthc) [inline packages/netlify-cms-core/src/actions/editorialWorkflow.js]: The unpublished entries(workflow page) should now load only once.

File: packages/netlify-cms-core/src/actions/editorialWorkflow.js (hunk 4 above)
Comment (erezrokah) [reply packages/netlify-cms-core/src/actions/editorialWorkflow.js]: This can happen when opening an entry in edit mode directly without going through the workflow tab first? Am I correct?

Comment (barthc) [reply packages/netlify-cms-core/src/actions/editorialWorkflow.js]: Yes, that's correct.

**Comment by barthc** [comment]
@erezrokah  did you find the PR @erquhart   referenced above?

File: packages/netlify-cms-backend-github/src/API.js [hunk 6]
```diff
@@ -459,33 +470,82 @@ export default class API {
...
+
+    // store new metadata
+    await this.storeMetadata(newContentKey, {
+      ...metaData,
+      pr: {
+        number: pr.number,
+        head: pr.head.sha,
+      },
+      branch: newBranchName,
+      version: CURRENT_METADATA_VERSION,
```
Comment (erezrokah) [inline packages/netlify-cms-backend-github/src/API.js]: This should be hard coded to '1' since we don't want it to change when someone updates `CURRENT_METADATA_VERSION` (see comment at the beginning of the function).

Comment (barthc) [reply packages/netlify-cms-backend-github/src/API.js]: ok, I will remove it.

**Comment by erezrokah** [comment]
Again, great job @barthc! Going to let @erquhart have a look at this before merging just to be sure.

**Comment by erezrokah** [comment]
> @erezrokah did you find the PR @erquhart referenced above?

Just saw this comment. Didn't find the PR, but we've discussed it and we're getting confident about merging this. Just letting @erquhart express his opinion the migration code first then it will be good to go.

**Comment by erezrokah** [comment]
Going to push this through as we have some more changes coming to the GitHub API
