### PR TITLE
fix(markdown-widget): support arbitrary component order

### LINKED ISSUE #5258: Markdown widget doesn't parse shortcodes if they're "out of order"
**Describe the bug**
When there are several shortcodes in a single markdown field, the markdown widget uses [`Map.find`](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js#L15-L23) to attempt to match the registered editor components' patterns against the remaining uneaten markdown. Because `Map.find` returns after the first instance that returns true, some valid shortcode matches can be "skipped" by the plugin, and parsed as plain text instead.

**To Reproduce**
1. Create a Netlify CMS collection that has a markdown widget field, and at least two custom editor components
2. Open the CMS page for that collection and create a new entity
3. Add two of each of your custom editor components, interleaved. That is:
    ```mdx
    Component One
    Component Two
    Component One
    Component Two
    ```
4. Save your changes and refresh the page

At least one of the four components will not be properly parsed as a shortcode, and will instead be rendered as plain text. Which one is determined by the order in the `Map` instance passed to `createShortcodeTokenizer` (which is nondeterministic, as immutable.js's Map is unordered).

**Expected behavior**
All four components should be parsed as custom components and receive the same visual treatment.

**Screenshots**
Actual behavior:
image

Expected behavior: 
image

**Applicable Versions:**

 - Netlify CMS version: 2.14.6
 - Git provider: GitHub
 - OS: macOS 11.1
 - Browser version: Firefox 87.0

 - Node.JS version: v14.5.4

**CMS configuration**
```yaml
local_backend: true
backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: pages
    label: Pages
    folder: src/markdown/pages
    extension: mdx
    format: frontmatter
    create: true
    slug: "{{fields.slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: Slug
        name: slug
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Heading
        name: heading
        widget: string
        required: false
      - label: Subheading
        name: subheading
        widget: string
        required: false
      - label: Show in Navigation Menu
        name: showInNavigation
        widget: boolean
        default: false
      - label: Navigation Menu Order
        name: navigationOrder
        widget: number
        default: 0
        # @see https://www.netlifycms.org/docs/configuration-options/#collections
        pattern:
          - "^[^-]?\\d+$"
          - "Cannot be a negative number"
      - label: Body
        name: body
        widget: markdown
    sortable_fields:
      - navigationOrder
      - slug
      - title
```

**Additional context**

### PR DESCRIPTION
**Pull request by SMores**
Fixes #5258

Reopen of #5259

## Summary
Updates `remarkShortcodes` to handle custom editor components occurring in
any order in a given markdown field.

Previously, `remarkShortcodes` (the remark tokenizer plugin in the markdown widget) was relying on [`Map.find`](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js#L15-L23) to attempt to match the registered editor components' patterns against the remaining uneaten markdown. Because Map.find returns after the first instance that returns true, some valid shortcode matches can be "skipped" by the plugin, and parsed as plain text instead.

This made it almost impossible to use multiple shortcodes in a single markdown field. At least one of them regularly gets "skipped" by the tokenizer.

This also updates the initial value returned by `getEditorComponents()` to correctly be an instance of `Map`, instead of an empty array.

### Unit Tests

I've updated the unit tests in the following ways:

1. I'm now passing an instance of `Map` as the second argument to `process`, instead of an array, because [that's what is actually passed in the code](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/lib/registry.js#L27)
2. I've added a new unit test that covers this case, relying on an `OrderedMap` to force a specific coincidental state that would have triggered the bug in the previous code (I verified that this new test does in fact fail under the previous code)

### Manual Inspection

I built this package locally and linked it into the project that I first identified this bug in, and verified that it resolved this issue and that I could not identify any new issues:

Before:
image

After:
image

## A picture of a cute animal (not mandatory but encouraged)

Some very tired dogs, as tribute:

63794410038__8567FE98-D096-4B00-A216-F180FCFCD1F7

### CODE REVIEW

**Comment by SMores** [comment]
Hey @erezrokah! Thanks for fixing the linting error. Any other thoughts on this guy? Would love to get it merged!

**Comment by erezrokah** [comment]
> Hey @erezrokah! Thanks for fixing the linting error. Any other thoughts on this guy? Would love to get it merged!

Hi @SMores, I've been wanting to figure why this doesn't break the image widget like the previous PR and wasn't able to do it yet.

Also, I haven't tested it thoroughly which I'd like to do as previously we broke the markdown widget for some users when doing similar changes.

File: packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js [hunk 1]
```diff
@@ -10,17 +10,16 @@ export function remarkParseShortcodes({ plugins }) {
...
-    const potentialMatchValue = value.split('\n\n')[0].trimEnd();
-    const plugin = plugins.find(plugin => {
-      match = value.match(plugin.pattern);
-
-      if (!match) {
-        match = potentialMatchValue.match(plugin.pattern);
-      }
-
-      return !!match;
-    });
```
Comment (SMores) [inline packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js:23]: @erezrokah I think I understand what was happening here, and what's happening with the image component.

Netlify CMS no longer auto-enables the multi-line flag for all plugin patterns, as of #3089. The image pattern is defined as `/^!\[(.*)\]\((.*?)(\s"(.*)")?\)$/`, which includes `^` and `$` characters. Since the image pattern doesn't have the multi-line flag, `$` is matching the end of the string, not the end of the line. That means any situation in which there is _any_ additional content after the image shortcode (e.g. a file-ending newline, like the example in #3077), the image pattern won't be matched.

I think there are a few paths forward. One would be to add a multiline flag to the image pattern (`/^!\[(.*)\]\((.*?)(\s"(.*)")?\)$/` -> `/^!\[(.*)\]\((.*?)(\s"(.*)")?\)$/m`), or to remove the `^` and `$` tokens, thereby removing the requirement that the entirety of the content needs to exactly match the shortcode. This is most likely insufficient, as there are probably a ton of plugins that have been developed based on this assumption that even if a multi-line flag isn't provided, it's safe to use `$` tokens in plugin patterns.

Another option is to include a more robust version of this single-line fallback in the new implementation:

```javascript
    const trimmedLines = value.split('\n\n').map(line => line.trimEnd());
    const matches = plugins
      .toList()
      .map(plugin => ({
        match: value.match(plugin.pattern) ||
          trimmedLines
            .map(line => line.match(plugin.pattern))
            .filter(match => !!match),
        plugin,
      }))
      .filter(({ match }) => !!match)
      .sort((a, b) => a.match.index - b.match.index);

    const { plugin, match } = matches.get(0) ?? {};
```

With this implementation, we can resolve the ordering issues from the previous implementation, while maintaining the "implicit multi line pattern" behavior.

Thoughts? If this second approach makes sense, I can write up some tests to capture this scenario, ensure that the new implementation is successful, and push up these changes!

Comment (SMores) [reply packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js:23]: Ah! There is, in fact, already a test capturing this scenario! It should have been failing on this PR, but the mock `EditorComponent` in `remarkShortcodes.spec.js` was still overriding the flags on `plugin.pattern` to add the multiline flag!

Test: https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkShortcodes.spec.js#L28-L32

Stale mock: https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkShortcodes.spec.js#L16-L19

Awesome. I'll push my proposed changes, along with the fixed mock!

File: packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkShortcodes.spec.js [hunk 2]
```diff
@@ -14,42 +16,53 @@ function process(value, plugins, processEat = () => {}) {
 }
 
 function EditorComponent({ id = 'foo', fromBlock = jest.fn(), pattern }) {
-  // initialize pattern as RegExp as done in the EditorComponent value object
-  return { id, fromBlock, pattern: new RegExp(pattern, 'm') };
+  return { id, fromBlock, pattern };
```
Comment (SMores) [inline packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkShortcodes.spec.js:19]: EditorComponent no longer overrides flags as of #3089

File: packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js (hunk 1 above)
Comment (erezrokah) [reply packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js]: Woo, this makes much more sense now.
Thank you for figuring it out. Do we want to match each line or just the first one as before?

Comment (SMores) [reply packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js]: I think we have to search all lines; the previous first-line-only implementation was also susceptible to the bug this PR is addressing.

In a first-line-only implementation, if Shortcode1 contains a `$` character, and Shortcode2 does not, we can imagine a `value` where Shortcode1 is found on line 2, and Shortcode2 is found on line 3. When searching for Shortcode1, we won't find it on line 2 (because of the `$`), and we won't find it on the fallback on line one. We will find Shortcode2 on line 3, however. This means we will skip Shortcode1 entirely.

**Comment by SMores** [comment]
Ok... I took another swing at this. Because we now care about the index in the document that a shortcode is found, it wasn't sufficient to fallback to searching individual lines to handle line anchors: if a shortcode _was_ found in an individual line, it would basically always have a `match.index` of `0`, meaning it would get sorted to the top and incorrectly supersede shortcodes that might have come first in the multiline search.

Instead, this goes back to modifying patterns as we get them, albeit in a more explicit way that I think accurately captures the intent. We now replace line anchors that might occur in a plugin pattern with a zero-width lookaround that accepts the line anchor _or_ a newline, which I think captures the API that we want to support. For example:

`/^<<my fancy shortcode>>$/` will be replaced with `/(?<=^|\n)<<my fancy shortcode>>(?=$|\n)/`

This will properly be found in any of the following documents:

```markdown
<<my fancy shortcode>>
```

```markdown
# This is a fancy shortcode

<<my fancy shortcode>>
```

```markdown
# This is a fancy shortcode

<<my fancy shortcode>>

That's all
```

And will _not_ match a document like this:

```markdown
You can add a fancy shortcode by typing <<my fancy shortcode>>!
```

We keep intact the flags passed in by the consumer. This is safe; the lookaround replacement is a noop for a regex with a multiline flag, which is the only flag that changes the meaning of line anchor tokens.

@erezrokah would love to get your thoughts!

File: packages/netlify-cms-core/src/valueObjects/EditorComponent.js [hunk 3]
```diff
@@ -28,8 +28,20 @@ export default function createEditorComponent(config) {
...
-    pattern,
+    // We allow consumers to specify line anchors (^ and $) without a
+    // multiline flag, but we need to be able to match in a multi-line
+    // context. In order to do so, we replace instances of line anchors
+    // with lookarounds that include \n's, so that non-multiline expressions
+    // still work as expected.
+    //
+    // Note: This is mocked in packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkShortcodes.spec.js;
+    // if you change it here, change it there as well!
+    pattern: new RegExp(
```
Comment (SMores) [inline packages/netlify-cms-core/src/valueObjects/EditorComponent.js:39]: Would it make sense to import this function directly into the remarkShortcodes spec file to avoid allowing these overrides to get out of sync again? Is it safe to just add this is a dev dependency for netlify-cms-widget-markdown and import it?

**Comment by stefanprobst** [comment]
does it makes sense to maybe also add some tips/recommendations to the editor widget docs about `pattern`? what would have helped me when trying to figure this out:
- the pattern is matched against *the whole remaining string*
- try to avoid `$`
- when needing to match across line breaks use something like `[^]*?`
- example: `/^<SideNote>\n([^]*?)\n<\/SideNote>/`

**Comment by SMores** [comment]
I actually think it's fine to use `$`, but when you do, you should use `m`! But yes, generally I think some more guidance would be good. I can draft something!

File: website/content/docs/custom-widgets.md [hunk 4]
```diff
@@ -118,29 +118,69 @@ CMS.registerEditorComponent(definition)
...
+  // Regex pattern used to search for instances of this block in the markdown document.
+  // Patterns are run in a multline environment (against the entire markdown document),
+  // and so generally should make use of the multiline flag (`m`). If you need to capture
+  // newlines in your capturing groups, you can either use something like
+  // `([\S\s]*)`, or you can additionally enable the "dot all" flag (`s`),
+  // which will cause `(.*)` to match newlines as well.
+  //
+  // Additionally, it's recommended that you use non-greedy capturing groups (e.g.
+  // `(.*?)` vs `(.*)`), especially if matching against newline characters.
+  pattern: /^<details>\s*?<summary>(.*?)<\/summary>\n\n(.*?)\n<\/details>$/ms,
```
Comment (SMores) [inline website/content/docs/custom-widgets.md:146]: @stefanprobst what do you think? I beefed up the example itself so that it could make more use of the features being described in the documentation. Open to edits!

File: website/content/docs/custom-widgets.md [hunk 5]
```diff
@@ -118,29 +118,69 @@ CMS.registerEditorComponent(definition)
...
+  // Regex pattern used to search for instances of this block in the markdown document.
+  // Patterns are run in a multline environment (against the entire markdown document),
+  // and so generally should make use of the multiline flag (`m`). If you need to capture
+  // newlines in your capturing groups, you can either use something like
+  // `([\S\s]*)`, or you can additionally enable the "dot all" flag (`s`),
+  // which will cause `(.*)` to match newlines as well.
+  //
+  // Additionally, it's recommended that you use non-greedy capturing groups (e.g.
+  // `(.*?)` vs `(.*)`), especially if matching against newline characters.
+  pattern: /^<details>$\s*?<summary>(.*?)<\/summary>\n\n(.*?)\n^<\/details>$/ms,
```
Comment (SMores) [inline website/content/docs/custom-widgets.md:146]: @stefanprobst what do you think? I beefed up the example itself so that it could make more use of the features being described in the documentation. Open to edits!

Comment (stefanprobst) [reply website/content/docs/custom-widgets.md:146]: thanks! this is great!

**Comment by erezrokah** [comment]
> Ok... I took another swing at this. Because we now care about the index in the document that a shortcode is found, it wasn't sufficient to fallback to searching individual lines to handle line anchors: if a shortcode _was_ found in an individual line, it would basically always have a `match.index` of `0`, meaning it would get sorted to the top and incorrectly supersede shortcodes that might have come first in the multiline search.

Can we somehow account for that in the sort? Either calculate the correct index ourselves or give less weight to per line matches?

> Instead, this goes back to modifying patterns as we get them, albeit in a more explicit way that I think accurately captures the intent. We now replace line anchors that might occur in a plugin pattern with a zero-width lookaround that accepts the line anchor _or_ a newline, which I think captures the API that we want to support.

I would try to avoid modifying users' patterns as we might break those or create a behavior that's unexpected.

**Comment by SMores** [comment]
We can definitely account for the offsets in the the matching function, it's just more complex than I initially drafted. My thought here is mostly that this is _already_ fairly hard-to-predict behavior, and that manipulating user's patterns might be the most robust approach. Like the proposed "single-line fallback match" approach doesn't match `/^<MyComponent>(\s\S*?)<\/MyComponent>$/` if the content is multi-line, but does if it's only a single line, which feels confusing to me, but I guess more closely matches the current behavior (if we pass this pattern through the manipulation I wrote, we end up with `/(?<=^|\n)<MyComponent>(\s\S*?)<\/MyComponent>(?=$|\n)/`, which _does_ match in both single and multi line contexts).

I can work on an approach that keeps track of line start positions, though; I do agree that it feels risky to manipulate patterns. Now that we've updated the documentation to note that folks should use the multiline flag for multiline contexts maybe all that matters is being narrowly backwards compatible.

File: packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js [hunk 6]
```diff
@@ -10,6 +10,33 @@ export function remarkParseShortcodes({ plugins }) {
...
+            line: line.trimEnd(),
+            start: previousLineStart + previousLineOriginalLength + 2,
+            originalLength: line.length,
+          },
+          ...acc,
+        ];
+      }, [])
+      .reverse()
+      .map(({ line, start }) => ({ line, start }));
+
```
Comment (SMores) [inline packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js]: @erezrokah I don't know how you all like to handle breaking changes, but I think dropping support for this behavior would be a great candidate for the next major version release! Especially now that it's not mentioned in the documentation. We would also have to update the pattern for the built-in image shortcode to turn on the multiline flag.

File: packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js [hunk 7]
```diff
@@ -10,17 +10,56 @@ export function remarkParseShortcodes({ plugins }) {
...
+          {
+            line: line.trimEnd(),
+            start: previousLineStart + previousLineOriginalLength + 2,
+            originalLength: line.length,
+          },
+          ...acc,
+        ];
+      }, [])
+      .reverse()
+      .map(({ line, start }) => ({ line, start }));
```
Comment (SMores) [inline packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js:38]: @erezrokah I don't know how you all like to handle breaking changes, but I think dropping support for this behavior would be a great candidate for the next major version release! Especially now that it's not mentioned in the documentation. We would also have to update the pattern for the built-in image shortcode to turn on the multiline flag.

**Comment by SMores** [comment]
Hey @erezrokah! Any further thoughts on this?

File: packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js (hunk 7 above)
Comment (erezrokah) [reply packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js:38]: I've opened https://github.com/netlify/netlify-cms/issues/5652 to track this.

**Comment by erezrokah** [comment]
> Hey @erezrokah! Any further thoughts on this?

Sorry for the delay. This is fully on my end and I'll try to follow up this week.

File: packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js [hunk 8]
```diff
@@ -10,17 +10,56 @@ export function remarkParseShortcodes({ plugins }) {
...
-    const potentialMatchValue = value.split('\n\n')[0].trimEnd();
-    const plugin = plugins.find(plugin => {
-      match = value.match(plugin.pattern);
+    // Plugin patterns may rely on `^` and `$` tokens, even if they don't
+    // use the multiline flag. To support this, we fall back to searching
+    // through each line individually, trimming trailing whitespace and
+    // newlines, if we don't initially match on a pattern. We keep track of
+    // the starting position of each line so that we can sort correctly
+    // across the full multilen matches.
+    const trimmedLines = value
```
Comment (erezrokah) [inline packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js:19]: I think we can simplify this function, I'll add another commit for it.
I also believe `start: 0` should be `start: -2` otherwise all the the `start` values will be shifted by `2`.

Comment (erezrokah) [reply packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js]: See https://github.com/netlify/netlify-cms/pull/5597/commits/c394df846abd9cb799a272b3ddacb2b204b1867c.

I tried using a regex to get the indices, but that came out ugly

File: packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js [hunk 9]
```diff
@@ -8,19 +8,64 @@ export function remarkParseShortcodes({ plugins }) {
...
+            value.match(plugin.pattern) ||
+            trimmedLines
+              .map(({ line, start }) => {
+                const match = line.match(plugin.pattern);
+                if (match) {
+                  match.index += start;
+                }
+                return match;
+              })
+              .find(match => !!match),
```
Comment (erezrokah) [inline packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js:64]: Would it make sense to break early from the `map` when we find a match? Since we're using `find` we only look for the first match correct?

Comment (erezrokah) [reply packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js]: Done in https://github.com/netlify/netlify-cms/pull/5597/commits/a0605cfc312b2473dbccb8887468aeea73ae01da

**Review by erezrokah — APPROVED** [review]
Sorry for the delay @SMores.

This looks good. I'll do some manual tests and probably release on Monday to minimize the risk

**Comment by SMores** [comment]
Still planning on releasing this week @erezrokah?

**Comment by erezrokah** [comment]
> Still planning on releasing this week @erezrokah?

Yes! Dependencies updates took a bit longer than usual yesterday...

**Comment by erezrokah** [comment]
Released in https://github.com/netlify/netlify-cms/releases/tag/netlify-cms%402.10.158, thanks @SMores for you patience and follow ups.

**Comment by SMores** [comment]
Thanks for all your feedback and support @erezrokah!! This is great!
