### PR TITLE
Prevent Overwriting Files with Same Slug Names

### LINKED ISSUE #1164: Prevent overwriting existing file
**- Do you want to request a *feature* or report a *bug*?**
BUG

**- What is the current behavior?**
When I add a file with the same title as an existing one and my slug equals title, the existing file is overwritten.

**- If the current behavior is a bug, please provide the steps to reproduce.**
make sure your slug equals title. add a file, choose a title that is already used by another file, save.
you have overwritten the existing file 

**- What is the expected behavior?**
- either: 
a new file is created (i.e. with counter to filename)
- or:
a warning that the file cannot be saved as it needs a unique title

Less urgent if #1069 were implemented.

### PR DESCRIPTION
**Pull request by brianlmacdonald**
Closes #1164.

Previously, when a file was added with the same title as an existing one and the slug equals title, the existing file is overwritten.

**- Summary**

This checks in `src/backends/backend.js` before the `entryObj` is created in `persistEntry` if there's an existing file with the same name. Throws an Error if there is. 

First, for `editorialWorkflow` mode, it checks in `window.repoFilesUnpublished` for preexisting entry. Next, it uses `this.implementation.getEntry`, checking if there's already a published entry in danger of being overwritten.

**- Test plan**
I created a file called `test`
screen shot 2018-04-09 at 1 26 30 pm

Saved the file successfully, and checked that it was in workflow.
screen shot 2018-04-09 at 1 27 32 pm

Then created a new file, also called `test`, tried to save it, and--
screen shot 2018-04-09 at 1 28 55 pm

Then instead, saved it as `Test 2`. 
screen shot 2018-04-09 at 1 30 00 pm

Then published it.
screen shot 2018-04-09 at 1 30 19 pm

Then created a new file, also called `Test 2`, and tried to save it, and --
screen shot 2018-04-09 at 1 30 34 pm

Error stopped it. All files are safe.

screen shot 2018-04-09 at 1 33 35 pm
screen shot 2018-04-09 at 1 33 41 pm

**- Description for the changelog**

Prevents file overwrite when encountering slug name collisions.

**- A picture of a cute animal (not mandatory but encouraged)**
Behold, a Fennec Fox at rest!
fennec_fox

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit f8bc33d7a3b1cb365a788c7715b9c6dabc67a30f

https://deploy-preview-1239--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit f8bc33d7a3b1cb365a788c7715b9c6dabc67a30f

https://deploy-preview-1239--cms-demo.netlify.com

File: src/backends/backend.js [hunk 1]
```diff
@@ -234,7 +233,20 @@ class Backend {
     .then(this.entryWithFormat(collection, slug));
   }
 
-  persistEntry(config, collection, entryDraft, MediaFiles, integrations, options = {}) {
+  async checkOverwrite(collection, slug, path, entryDraft) {
+    const errorMessage = "Oops, duplicate filename found. Please choose a unique name."
+    const existingEntry = window.repoFilesUnpublished.find(e => {
```
Comment (tech4him1) [inline src/backends/backend.js]: Unfortunately, `repoFilesUnpublished` is an implementation detail of the test-repo backend, not something most backend use, so this will have to be checked using a different method.

Comment (tech4him1) [reply src/backends/backend.js]: To get them for any backend type, you should be able to use `backend.unpublishedEntries()`.

Comment (tech4him1) [reply src/backends/backend.js]: It may be easier and more performant, however, to just check for the specific entry that you want using `unpublishedEntry()`, instead of filtering them yourself.

Comment (brianlmacdonald) [reply src/backends/backend.js]: @tech4him1 the problem is when `backend.unpublishedEntry` uses `implementation.unpublishedEntry` it throws an error if there is no entry found.

```
unpublishedEntry(collection, slug) {
    const entry = window.repoFilesUnpublished.find(e => (
      e.metaData.collection === collection.get('name') && e.slug === slug
    ));
    if (!entry) {
      return Promise.reject(new EditorialWorkflowError('content is not under editorial workflow', true));
    }
    return Promise.resolve(entry);
  }
```

screen shot 2018-04-09 at 3 59 43 pm
Ideas to get around this?

Comment (brianlmacdonald) [reply src/backends/backend.js]: @tech4him1 badass!

**Comment by tech4him1** [comment]
@brianlmacdonald Can you go ahead and remove the contributor addition commit from this PR to fix the merge conflict -- I've added you separately.

**Comment by tech4him1** [comment]
@brianlmacdonald Do you mind if I rebase this so the commit history and diff is clean?

**Comment by erquhart** [comment]
With [explicit slug editing](#445) on the horizon, I'm now thinking the goals of this PR should be met as a part of slug validation.

**Comment by tech4him1** [comment]
@erquhart I always assumed this was intended to be a stop-gap until we explicit slug editing was added?

**Comment by erquhart** [comment]
Yeah, see my edit. I'm thinking this is good to go.

File: src/backends/backend.js [hunk 2]
```diff
@@ -250,11 +269,7 @@ class Backend {
       }
       const slug = slugFormatter(collection.get("slug"), entryDraft.getIn(["entry", "data"]), config.get("slug"));
       const path = selectEntryPath(collection, slug);
-      entryObj = {
-        path,
-        slug,
-        raw: this.entryToRaw(collection, entryDraft.get("entry")),
-      };
+      entryObj = await this.checkOverwrite(collection, slug, path, entryDraft);
```
Comment (erquhart) [inline src/backends/backend.js]: Instead of implicitly constructing and returning the entry object from `checkOverwrite`, we should construct the entry object here either before or after the check.

Comment (erquhart) [reply src/backends/backend.js]: Working on an update commit.

**Comment by erquhart** [comment]
Added a commit that does two things:

1. References the identifier field reusing the same logic as the slug formatter that writes the identifiers, rather than only checking the "title" field
2. References the identifier field's label in an extended error message to ensure the user knows which field needs to be changed and why

@brianlmacdonald @tech4him1 if both of you can give a review we can get this merged.

File: src/backends/backend.js [hunk 3]
```diff
@@ -41,23 +41,28 @@ class LocalStorageAuthStore {
...
+const validIdentifierFields = ["title", "path"];
 
-    const identifier = identifiers.find(ident => ident !== undefined);
+const getIdentifierKey = entryData => {
+  const keys = validIdentifierFields.map(field => {
+    return entryData.findKey((_, key) => {
+      return key.toLowerCase().trim() === field;
+    });
+  });
+  return keys.find(key => entryData.get(key) !== undefined);
```
Comment (tech4him1) [inline src/backends/backend.js]: Is there a reason we can't use the old logic here, where we return the values (on line 48), instead of having to run `entryData.get` again here?

Comment (tech4him1) [reply src/backends/backend.js]:
```js
const keyVals = validIdentifierFields.map(field => {
  return entryData.find((_, key) => {
    return key.toLowerCase().trim() === field;
  });
});
return keyVals.find(key => key !== undefined);
```

Comment (erquhart) [reply src/backends/backend.js]: Agreed, I believe I was thinking we were lowercasing and trimming the return value for some reason, but that isn't the case.

**Comment by erquhart** [comment]
Reverted to fix #1377.

**Comment by brianlmacdonald** [comment]
@erquhart sure. Was this working before because it was running through the test-repo?

**Comment by erquhart** [comment]
Could have sworn I tested against real backends, but maybe it was just the test repo.
