### PR TITLE
fix(netlify-cms-core): wrap navigations in lists for better a11y

### LINKED ISSUE #1488: Use list items for accessibility #a11y
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

HTML elements in the app which ought to be lists are actually nested divs ie in header, aside and main.

This is a continuation of #1486 'Use HTML elements for accessibility'. I put it in a separate issue as it is considerably more complex.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Using a screenreader, a list of items should be announced but they won't be, as it's nested divs. Alternatively, view source and look inside the header, sidebar and main areas.

**- What is the expected behavior?**

A screenreader announces a list of options, which helps navigation

**- Please mention your versions where applicable.**

Netlify CMS version: 2.0.0-dev-dev
Browser version: 61.0

Node.JS version: v8.9.1
Operating System: MacOS 10.13.5

### PR DESCRIPTION
**Pull request by alexandernanberg**
**Summary**

Closes #1488 

This PR only affects the markup, the style should look identical

**Test plan**

N/A

### CODE REVIEW

File: packages/netlify-cms-core/src/components/Collection/Sidebar.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ const SidebarHeading = styled.h2`
 const SearchContainer = styled.div`
   display: flex;
   align-items: center;
-  margin: 0 8px;
+  margin: 0 12px;
```
Comment (alexandernanberg) [inline packages/netlify-cms-core/src/components/Collection/Sidebar.js]: Added this in because the search field didn't align entirely with the title and items

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit b8065af8b9f00629311b5be99dbecd775f9aafdb

https://deploy-preview-1903--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit b8065af8b9f00629311b5be99dbecd775f9aafdb

https://deploy-preview-1903--cms-demo.netlify.com
