### PR TITLE
Fix deletion for the `test-repo` backend.

### LINKED ISSUE #537: Cannot delete test post(s) in example seed data
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Cannot delete post from test example.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Create new post under `posts/entries/new`.
2. Write a post with a title and a body (title and body are both required here and does not alert the user that the fields are empty)
3. Hit save.
4. Once loaded, hit delete.

**- What is the expected behavior?**
The post should be deleted. @erquhart Mentioned that the posts are stored in-memory, so this should clear the entry in-memory and re-render the deleted post.
**- Please mention your node.js, and operating system version.**
This build has been deployed to netlify. I am not sure what Node version/OS they use to host the app.

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Fixes #537.

Deletion was added in #485, but the function for the `test-repo` backend was `deleteEntry` instead of `deleteFile` like it was supposed to be. Therefore, files could not be deleted.

Also, setting the key for a deleted file to `undefined` did not really remove that file from the object, so there were then errors stating `file.content` is not defined. `delete`ing the "file" from the object fixes this bug.

**- Test plan**

Manually tested with `npm run start`, then adding and deleting posts. Also deleted some default posts.

**- Description for the changelog**

Fix broken entry deletion for the `test-repo` backend.

### CODE REVIEW

File: src/backends/test-repo/implementation.js [hunk 1]
```diff
@@ -93,10 +93,10 @@ export default class TestRepo {
     return Promise.resolve();
   }
 
-  deleteEntry(path, commitMessage) {
+  deleteFile(path, commitMessage) {
     const folder = path.substring(0, path.lastIndexOf('/'));
     const fileName = path.substring(path.lastIndexOf('/') + 1);
-    window.repoFiles[folder][fileName] = undefined;
+    delete window.repoFiles[folder][fileName];
```
Comment (tech4him1) [inline src/backends/test-repo/implementation.js]: @Benaiah Are you OK with using `delete` directly, or not?

Comment (Benaiah) [inline src/backends/test-repo/implementation.js]: Yeah, that's fine with me.
