### PR TITLE
fixes #1564, #1565

### LINKED ISSUE #1564: Writing posts with GitLab as backend is broken
**- Do you want to request a *feature* or report a *bug*?**
Bug, see below for a detailed analysis. Pull request is coming too.

**- What is the current behavior?**
Using GitLab as backend doesn't work. Creating or editing posts is not possible.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Use the config.yml above and try to create new posts for a static website. No error is shown by netlify-cms, but there are no new commits in the repository.

**- What is the expected behavior?**
It should be possible to create and edit posts with netlify-cms.

**- Bug analysis**
If you try to publish a new post, a POST request with the following body is sent to the GitLab API.

```json
{
    "branch": "master",
    "commit_message": "Update Pentest “2017-03-01-Hooking”",
    "actions": [{
        "action": "update",
        "file_path": "Pentest/_posts/2017-03-01-Hooking.md",
        "content": {},
        "encoding": "base64"
    }]
}
```
The problem is the empty `content` property inside the request body of the POST request. The response has a status code 500. I don't know why the frontend doesn't show any error but instead shows a message that everything went well. I think the request promise is not rejected although the status code is 500.

I could track down the bug. It is introduced by @erquhart ([Blame](https://github.com/netlify/netlify-cms/blame/4d6a1ebf8d171ec81f18a0558b5e2423383ea736/packages/netlify-cms-backend-gitlab/src/API.js#L188))
The problem is that the `content` constant is a Promise and not the value of `item.raw`. I will make a Pull request to fix this.

Please take a look at the GitHub implementation as well. I didn't test it, but I think it is working, because the Promise is handled correctly.([Relevant GitHub code](https://github.com/netlify/netlify-cms/blame/master/packages/netlify-cms-backend-github/src/API.js#L714))

**- Please mention your versions where applicable.**

Netlify CMS version: 2.0.6
Browser version: Chrome 66, Firefox 61

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: gitlab
  branch: master # Branch to update (optional; defaults to master)
  repo: [repository]
  auth_type: implicit # Required for implicit grant
  app_id: [applicationId] # Application ID from your GitLab settings
  api_root: https://gitlab.lan/api/v4
  base_url: https://gitlab.lan
  auth_endpoint: oauth/authorize
```

### LINKED ISSUE #1565: Uploading images with GitLab as backend is broken
**- Do you want to request a *feature* or report a *bug*?**
Bug, see below for the bugfix. Pull request is coming.

**- What is the current behavior?**
Uploading images with GitLab as backend is broken.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Use GitLab as backend and try to upload a new image.

**- What is the expected behavior?**
The image is uploaded and commited by the cms.

**- Bugfix**
Use the `result` function instead of `get` in the `uploadAndCommit` function (see [here](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-backend-gitlab/src/API.js#L188)). I will create a pull request to fix this issue.

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: gitlab
  branch: master # Branch to update (optional; defaults to master)
  repo: [repository]
  auth_type: implicit # Required for implicit grant
  app_id: [applicationId] # Application ID from your GitLab settings
  api_root: https://gitlab.lan/api/v4
  base_url: https://gitlab.lan
  auth_endpoint: oauth/authorize
```

### PR DESCRIPTION
**Pull request by Kavakuo**
**- Summary**
This fixes the netlify-cms with GitLab as backend. Now it is possible to upload images and publish posts using the CMS.

**- Test plan**
Publishing issue (#1564):
Prior to this pull request, the `content` variable, which is passed to the `JSON.stringify()` method later, was a Promise. `JSON.stringify` transformed it to `{}` instead of the content in the markdown text editing field. Now the value is extracted out of the Promise by using the `await` operator ([source code](https://github.com/netlify/netlify-cms/blob/d08e5f5183dec997cbd2bb602b1584690ab0c324/packages/netlify-cms-backend-gitlab/src/API.js#L189-L191)).

Image uploading issue (#1565):
Prior to this pull request, it wasn't possible to upload images with the CMS. If `item`, the argument of the `uploadAndCommit` function is an AssetProxy, the `get` function does not bind `item` to the `this` variable inside the `item.toBase64()` function. As result the function crashes at the execution of `this.fileObj`.
Use `result` instead of `get` to resolve the issue ([source code](https://github.com/netlify/netlify-cms/blob/d08e5f5183dec997cbd2bb602b1584690ab0c324/packages/netlify-cms-backend-gitlab/src/API.js#L188)).

**- Description for the changelog**
- Extract the value of the Promise instead of passing the Promise to `JSON.stringify()` (#1564, [source code](https://github.com/netlify/netlify-cms/blob/d08e5f5183dec997cbd2bb602b1584690ab0c324/packages/netlify-cms-backend-gitlab/src/API.js#L189-L191))
- Use `result` instead of `get` to get the function work with `AssetProxy`. (#1565, [source code](https://github.com/netlify/netlify-cms/blob/d08e5f5183dec997cbd2bb602b1584690ab0c324/packages/netlify-cms-backend-gitlab/src/API.js#L188))

If you have any questions, let me know.

Closes #1564, closes #1565.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit d08e5f5183dec997cbd2bb602b1584690ab0c324

https://deploy-preview-1566--netlify-cms-www.netlify.com

File: packages/netlify-cms-backend-gitlab/src/API.js [hunk 1]
```diff
@@ -185,7 +185,11 @@ export default class API {
   toBase64 = str => Promise.resolve(Base64.encode(str));
   fromBase64 = str => Base64.decode(str);
   uploadAndCommit = async (item, { commitMessage, updateFile = false, branch = this.branch, author = this.commitAuthor }) => {
-    const content = get(item, 'toBase64', partial(this.toBase64, item.raw))();
+    let content = result(item, 'toBase64', partial(this.toBase64, item.raw));
+    if (content instanceof Promise) {
+      content = await content;
+    }
+
```
Comment (tech4him1) [inline packages/netlify-cms-backend-gitlab/src/API.js]: We can remove the `if` check here and just do `await result(...` directly.


> If the value of the *expression* following the `await` operator is not a `Promise`, it's converted to a resolved Promise.
>
> <sup>~https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await</sup>

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit d08e5f5183dec997cbd2bb602b1584690ab0c324

https://deploy-preview-1566--cms-demo.netlify.com

File: packages/netlify-cms-backend-gitlab/src/API.js (hunk 1 above)
Comment (Kavakuo) [reply packages/netlify-cms-backend-gitlab/src/API.js]: Good to know. Added a commit to change this.

**Comment by tech4him1** [comment]
Looks like Travis broke for some reason not connected to the PR -- we should be good to merge.

**Comment by erquhart** [comment]
Yep, bug + fix: https://github.com/facebook/jest/issues/6766#issuecomment-408344243
