### PR TITLE
fix null on markdown image alt

### LINKED ISSUE #956: Image alt text in markdown widget defaults to null
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

When an image is inserted in the markdown editor (rich text mode), the alt text is persisted as `null` if left blank.

**- If the current behavior is a bug, please provide the steps to reproduce.**

* create a new entry that uses the markdown widget
* insert an image before making any other changes in the widget
* switch to markdown view
* note that alt value is "null" as a string

**- What is the expected behavior?**

* alt value should be an empty string

**- Please mention your CMS, node.js, and operating system version.**

CMS 1.0.3

### PR DESCRIPTION
**Pull request by leonardodino**
**Summary**

closes #956
was getting `null` on my markdowns, when not entering any text 🐛 
made the one of the [image serializers](https://github.com/netlify/netlify-cms/blob/a262bcef530532d710540af16d83e9a9dcaaa597/packages/netlify-cms-widget-markdown/src/serializers/remarkImagesToText.js#L19) mirror [another one](https://github.com/netlify/netlify-cms/blob/a262bcef530532d710540af16d83e9a9dcaaa597/packages/netlify-cms-editor-component-image/src/index.js#L11
), from this very repository.

**Test plan**

1. manually added markdown line and snapshot.
2. `yarn jest`, it breaks (sending `null` as when empty)
3. fixed it! 💪 

before:
```diff
@@ -22,9 +22,9 @@
- <p>![](https://pbs.twimg.com/profile_images/678903331176214528/TQTdqGwD.jpg)</p>",
+ <p>![null](https://pbs.twimg.com/profile_images/678903331176214528/TQTdqGwD.jpg)</p>",
```

after: **passes**.

**A picture of a cute animal (not mandatory but encouraged)**

null

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit baffbac87ad26f8c3ffd731f49318a2943b86b6f

https://deploy-preview-1778--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit baffbac87ad26f8c3ffd731f49318a2943b86b6f

https://deploy-preview-1778--cms-demo.netlify.com

File: packages/netlify-cms-widget-markdown/src/serializers/remarkImagesToText.js [hunk 1]
```diff
@@ -15,8 +15,8 @@ export default function remarkImagesToText() {
         child.children.length === 1 &&
         child.children[0].type === 'image'
       ) {
-        const { alt = '', url = '', title = '' } = child.children[0];
-        const value = `![${alt}](${url}${title ? ' title' : ''})`;
+        const { alt, url, title } = child.children[0];
+        const value = `![${alt || ''}](${url || ''}${title ? ' title' : ''})`;
```
Comment (leonardodino) [inline packages/netlify-cms-widget-markdown/src/serializers/remarkImagesToText.js]: i've kept the implementation of `title` prop unchanged.
but it probably should look like this: ``${title ? ' ' + title : ''}``

Comment (erquhart) [reply packages/netlify-cms-widget-markdown/src/serializers/remarkImagesToText.js]: Ha, yeah that's busted. Can you just drop the title stuff for now? It doesn't really seem to be supported elsewhere in our serialization process, and no one has complained that it's completely broken.

Comment (leonardodino) [reply packages/netlify-cms-widget-markdown/src/serializers/remarkImagesToText.js]: sure! will do (:

Comment (leonardodino) [reply packages/netlify-cms-widget-markdown/src/serializers/remarkImagesToText.js]: done @erquhart!

**Comment by erquhart** [comment]
Looks great, thanks!
