### PR TITLE
Fix some block style buttons not highlighted when clicking on the equivalent blocks in the editor

### LINKED ISSUE #5338: Toolbar buttons for some block styles are not highlighted on active
**Notes**: This is related to issue #761 

**Describe the bug**

There are two parts to this issue:
- When selecting a block of text in the editor and toggle it to Quoteblock, Bulleted list or Numbered list using toolbar buttons, the buttons are not highlighted. However, the text was converted properly to the chosen text style.
- When clicking away from an existing quoteblock, bulleted list or numbered list, then select or click on them again to focus, the toolbar button is not highlighted either.

**To Reproduce**

Steps to reproduce the behavior. For example:
1. Create a new post
2. Make sure that the editor is set to Rich Text.
3. Enter four lines, with each line separated by an Enter key: Heading 2, Quote block, Bulleted list, Numbered list.
4. Select the “Heading 2” text and click the Heading 2 button in the toolbar. The text turns into heading 2 and the button is darkened.
5. Select the “Quoteblock” and click the Quote block button in the toolbar. The text turns into a quoteblock but the button is not highlighted.
6. Click away from the “Quoteblock” text and click on it again. The button is not highlighted either.
7. Do the same thing for “Bulleted list” and “Numbered list” and you should see the same issue.

Repeat the process above, but change step 1 to edit an existing post. The issue still remains.

**Expected behavior**

When selecting a piece of text and click Quoteblock, Bulleted list or Numbered list button, the button should be highlighted to signal to users that the text has really been converted from paragraph to the above styles.

Similarly, when focusing an existing quoteblock, bulleted list or numbered list, the button should also be highlighted so users understand that if they click the button again, they will turn the text back to a paragraph.

**Screenshots**

block-buttons-not-highlighting-on-click

**Applicable Versions:**

 - Netlify CMS version: Netlify CMS 2.10, Netlify CMS app 2.14
 - Git provider: GitHub,
 - OS: MacOS Catalina
 - Browser version: Chrome 90

 - Node.JS version: 12.6

**CMS configuration**

```yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["software development", "programming"],
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
```
**Additional context**

Here's what I found when examining the toolbar buttons with React Developer tools:

The component that renders the toolbar button and handles click event for changing text styles is called `<StyledToolbarButton />`.

It also has a prop `isActive` that takes a boolean value. If this value is true, the button takes a color rgb(30, 37, 50) aka highlighted. Otherwise, the value is by default false and the button's color is inherited.

styled-toolbar-button-components

This prop's value is changed when we focus on a piece of text in the editor by either clicking or selecting. As you can see, when I focus on the Heading 2 text, the `isActive` prop in the Heading button component changes to `true`. 

For reasons that I don't understand yet, in the Quoteblock, Bulleted list and Numbered list button components, this prop's value remains `false` even when the corresponding text style in the editor is focused.

Is my description clear enough @erquhart ?

### PR DESCRIPTION
**Pull request by bytrangle**
fixes #5338 

**Summary**
## Summary

This PR attempts to fix the problem with Netlify Markdown widget wherein the toolbar buttons for quote, bulleted list and numbered list are not highlighted when clicking on the corresponding block in the editor. 

## Notes

All files mentioned are located inside packages/netlify-cms-widget-markdown/src/MarkdownControl.
When referencing Slate's documentation, please visit the 0.47 version. Netlify CMS app uses Slate 0.47, and Slate was rewritten from the ground up after this version. Most of the functionalities mentioned below don't apply to versions after 0.47.

## Why the quote toolbar button is not highlighted?

Here is a tree diagram starting from the `<VisualEditor>` component.

visual-editor-component-tree

The Quote toolbar button is just a presentation component. It has several props, one of which is  isActive whose boolean value determines the color of button. If true, the button color is #1e2532. This is what end users see as being highlighted. If false, the button color is inherited from its parent, the `<Toolbar>` component.

```
// ToolbarButton.js
const StyledToolbarButton = styled.button`
  /* ... */
  color: ${props => (props.isActive ? '#1e2532' : 'inherit')}
  /* ... */
`

function ToolbarButton({ isActive }) {
  return (
    <StyledToolbarButton
      isActive={isActive}
    >
      {...}
    </StyledToolbarButton>
  )
}
```

And what determines the value of this prop? It is passed from `<Toolbar>` , and equal to the what is returned from calling function `hasBlock(type`) , setting type=quote.

This function `hasBlock(type)` is in turn a prop of `<Toolbar>` component passed down from `<VisualEditor>`.

```
// Toolbar.js
export default class Toolbar extends React.Component {
  render() {
    const { hasBlock = () => {} } = this.props
    return (
      <ToolbarContainer>
        <div>
          {isVisible('quote') && (
            <ToolbarButton 
              isActive={hasBlock('quote')}
            />
          )}
        </div>
      </ToolbarContainer>
    )
  }
}
```

Here is what `hasBlock` method do in `<VisualEditor>` class:

```
// VisualEditor.js
export default class Editor extends React.Component {
  // ...
  hasBlock = type => this.editor && this.editor.hasBlock(type);
  render() {
    return ()
  }
}
```

The property `editor` here is a top-level controller that holds the data inside the Slate editor, and all the handlers that determine its behavior.

Here, we can see that this controller has a first-class method named `hasBlock`. But where does this `hasBlock` come from?

It turns out that this handler comes from a plugin we add to our editor. 

Slate editor takes a prop called plugins whose value is an array of plugins. 

```
// VisualEditor.js
// ...
import plugins from './plugins/visual';
// ...
export default class Editor extends React.Component {
  constructor(props) {
    // ...
    this.plugins = plugins({
      // ...
    })
  }
  render() {
    return (
      <div>
        {...}
        <Slate plugins={this.plugins}/>
      </div>
    )
  }
}
```

Each plugin is just a plain Javascript object containing one or more functions that control the logic of our editor.

```
// plugins/visual.js
import CommandsAndQueries from './CommandsAndQueries';

function plugins({ getAsset, resolveWidget, t}) {
  return [
    // ...
    CommandsAndQueries({ defaultType }) // defaultType here is 'paragraph'
    // ...
  ]
}
```

In this case, the hasBlock handler of the editor comes from a plugin object called CommandsAndQueries.

```
// plugins/CommandsAndQueries.js
function CommandsAndQueries({ defaultType }) {
  return {
    queries: {
      // ...
      hasBlock(editor, type) {
        return editor.value.blocks.some(node => node.type === type);
      }
    }
  }
}
```

When we define `hasBlock` inside the `queries` property, it will be made available as a method on the editor object. That's why we can call this.editor.hasBlock directly from the VisualEditor component.

Let's add `console.log` to the `hasBlock` function to see what it does.

```
hasBlock(editor, type) {
        return editor.value.blocks.some(node => {
          console.log({ node });
          return node.type === type;
        });
      },
```

Go to the Netlify CMS admin, click on an existing blog post or create a new one. Click on any paragraph block, then click the Quote button.

The block node that receives the click has a type paragraph. In order for the Quote button to be highlighted, it has to be of type quote.

quoteblock-paragraph

What happened? Inspecting the DOM tree, we can see that our quote block is actually a p element wrapped inside a blockquote element.

The reason is `editor.value` gets the current data in the Slate editor. `editor.value.block` retrieves the lowest depth block node in the current selection, or the `<p>` element in this case, not `<blockquote>`.

This means calling `hasBlock('quote')` will aways returns false, thereby setting isActive prop in the `<ToolbarButton>` component to false. As a result, the quote toolbar button is never highlighted.

## Resolution

To check if a node is child of a blockquote , we need to go up and check its parent node type.

But first, let's create a new query for checking quote block. The reason is `hasBlock` function is also called in six other buttons: heading 1 to 6. Determining if a block node is a heading is more straightforward and doesn't require checking its parent node.

```
// plugins/CommandsAndQueries .js
function CommandsAndQueries({ defaultType }) {
  return {
    queries: {
      hasQuote(editor, quoteLabel) {
        const { value } = editor;
        const { document, blocks } = value;
        return blocks.some(node => {
          const { key: descendantNodeKey } = node;
          const parent = document.getClosest(
            descendantNodeKey,
            parentNode => parentNode.type === quoteLabel,
          );
          console.log({ parent });
          return !!parent;
        });
      },
    }
  }
}
```

Then, in the `<VisualEditor>` component, add a `hasQuote` method, and pass it as prop to the `<Toolbar>` component.

```
// VisualEditor.js
export default class Editor extends React.Component {
  // ...
  hasQuote = type => this.editor && this.editor.hasQuote(type);
  render() {
    return (
      // ...
        <Toolbar hasQuote={this.hasQuote} />
      // ...
    )
  }
}
```

Finally, in the `<Toolbar>` component, extract the `hasQuote` prop. Then look for the `<ToolbarButton>` component for quote and call hasQuote in the isActive prop.

```
// Toolbar.js
export default class Toolbar extends React.Component {
  render() {
    const { hasQuote = () => {} } = this.props
  }
  return (
    {isVisible('quote') && (
      <Toolbarbutton
        // ...
        isActive={hasQuote('quote')}
      />
    )}
  )
}
```

## What about list blocks
It has almost the same as quote blocks, except that a list block contains three levels:

```
<ul>
  <li>
    <p>Bulleted list 1</p>
  </li>
  <li>
    <p>Bulleted list 2</p>
  </li>
</ul>
```

When clicking on a list block, the node that gets the click is the paragraph element. So we have to travel up twice:
- check if its parent is of type `list-item`
- check if its grandparent is of type `bulleted-list` or `numbered-list`

**Test plan**

### CODE REVIEW

File: packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js [hunk 1]
```diff
@@ -71,6 +71,37 @@ function CommandsAndQueries({ defaultType }) {
       hasInline(editor, type) {
         return editor.value.inlines.some(node => node.type === type);
       },
+      hasQuote(editor, quoteLabel) {
+        const { value } = editor;
+        const { document, blocks } = value;
+        return blocks.some(node => {
+          const { key: descendantNodeKey } = node;
+          const parent = document.getClosest(
```
Comment (erezrokah) [inline packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js:79]: I think this has a false positive (marks a block as a quote when it shouldn't) in the following structure:
image

Would the following code work for both use cases:
```js
return blocks.some(node => {
  const parent = document.getParent(node.key);
  return parent && parent.type == quoteLabel;
});
```

File: packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js [hunk 2]
```diff
@@ -71,6 +71,37 @@ function CommandsAndQueries({ defaultType }) {
...
+            parentNode => parentNode.type === quoteLabel,
+          );
+          return !!parent;
+        });
+      },
+      hasListItems(editor, listType) {
+        const { value } = editor;
+        const { document, blocks } = value;
+        return blocks.some(node => {
+          const { key: lowestNodeKey, type: lowestNodeType } = node;
```
Comment (erezrokah) [inline packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js:90]: Similar to the above comment this can mark a list item as both a bulleted list and a numbered list:
image

Would the following work:
```js
return blocks.some(node => {
  const parent = document.getParent(node.key);
  const grandParent = parent && document.getParent(parent.key);

  return (
    node.type === 'paragraph' &&
    parent?.type === 'list-item' &&
    grandParent?.type === listType
  );
});
```

**Review by erezrokah — CHANGES_REQUESTED** [review]
@bytrangle this is amazing!

Thank you for the detailed breakdown of the underlying issue and for the suggested solution.
Great work and your analysis is 💯 

I added two comments regarding use cases I think the current solution is missing.
Please let me know what you think

File: packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js (hunk 2 above)
Comment (bytrangle) [reply packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js:90]: It works. Thanks for your suggestion, although I'm starting to feel like the lax schema in Netlify CMS' s will open up new unexpected UI problems in the future.

File: packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js (hunk 1 above)
Comment (erezrokah) [reply packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js:79]: > Hello @erezrokah . If I understand correctly:
> 
> * the first `test` is a quote block. Then you hit Enter, and the quote block continues.
> * On the the second `test`, you give it a `list` style.
> 
> Technically, the second `test` is still in quoteblock.

Correct, the thing is if you click quote block again it creates another quote block within the list item (instead of removing the root one).
We can discuss if that's the correct behavior, but as long as it is the `active` property should reflect that.

> Your suggestion works and I'm going to implement that but is it necessary to check that parent is defined? Because every thing inside the editor has a `Document` object as a parent by default. The heading block, paragraph block, their parent is the `Document`. If you give it a list or quote style, then it has a new parent. But what I mean is that the `parent` will always be defined.

You're correct. I was thinking root level objects might not have a parent, but in this context it should always be defined.


> Should I open an issue to discuss that?

What you've discovered is related to my first response in this comment. Please open a new issue for it as I also think nesting inside quote blocks it strange.

File: packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js (hunk 2 above)
Comment (erezrokah) [reply packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js:90]: How do you suggest we tackle the schema issue. We've been wanting to update slate to the latest version but it's quite a heavy lift. We could re-enable the tests here https://github.com/netlify/netlify-cms/blob/26cd552746d6294387b9bdd961a73d5a531bf665/packages/netlify-cms-widget-markdown/src/serializers/__tests__/commonmark.spec.js#L67
and see what's failing too

Comment (bytrangle) [reply packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js:90]: I haven't had a concrete idea, but at the very least, `quote` and `list-item` blocks shouldn't have heading, code block, table etc as child nodes. The behavior of Backspace and Enter is also unpredictable. Is there a dedicated thread where we can discuss more about schema and document transformation in general?

Comment (erezrokah) [reply packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js:90]: > Is there a dedicated thread where we can discuss more about schema and document transformation in general?

We have a few issues about our editor various quirks, but I don't think we have a central one. Would you like to open it and start a discussion?

Comment (bytrangle) [reply packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js:90]: I've discovered another issue:

If I'm in a `list-item` block, then click any Heading button. Now, the List button will be dimmed and the Heading button highlighted.

quote-block-inside-list

That's because one of the condition for active list is the lowest node has to be `paragraph` block. But now the lowest node has become a `heading` block, because the schema allows that.

Should I remove `node.type === 'paragraph'` condition? The downside is that both Heading and List buttons will be highlighted, which is potentially confusing to end users.

Comment (erezrokah) [reply packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js:91]: > Should I remove `node.type === 'paragraph'` condition? The downside is that both Heading and List buttons will be highlighted, which is potentially confusing to end users.

I think removing `node.type === 'paragraph'` makes sense due to the current behavior.

**Review by erezrokah — APPROVED** [review]
Thanks @bytrangle, this is good to go 🚀

**Comment by bytrangle** [comment]
> Thanks @bytrangle, this is good to go 🚀

Thank you @erezrokah for your patience. And I have no idea how Netlify CMS team can be so efficient at handing PRs.
