### PR TITLE
editor fast follow

### LINKED ISSUE #575: Markdown editor fast fixes - 0.5.0 beta
This issue can be appended to include various bugs that are found in the new editor. When fast fixes are complete, any remaining issues here can be converted to standalone issues.

#### Inline node processing issues
Inline nodes need to be processed alongside surrounding text, and be subject to surrounding marks, while still having their children processed as required.
- [x] inline images become text in the visual editor
- [x] markdown images within links used to display as images, now they display as text
- [x] marks around links cause the links to become text in the visual editor
- [x] marks applied to inline code, e.g. \*\*\`test\`\*\*, break in the visual editor

#### Escaping issues
- [x] when converting markdown to Remark, don't parse markdown entities within raw html
- [x] when converting Slate to Remark, escape all markdown entities except those in raw html
- [x] markdown images broken by unintelligent escaping because `![` becomes `!\[`
- [x] visual editor doesn't distinguish between newline sequence (literal `\n`) and line break
- [x] html entities are decoded by the visual editor (not just visually, but in the source)
- [x] line break entities (trailing backslash) are visible in visual editor
- [x] markdown entities within code blocks should not be escaped
- [x] markdown entities within raw html should not be escaped
(trailing double space or backslash)
- [x] inactive markdown entities (like a literal asterisk or backslash) are unnecessarily escaped

#### UX issues
- [x] clicking below a trailing shortcode block in the visual editor should set focus in a paragraph
- [x] trim trailing empty paragraphs during remark -> markdown

#### Parsing issues
- [x] standalone URLs in markdown are converted to links in the visual editor
- [x] links containing images break the visual editor when attempting to backspace them
    (addressed here: https://github.com/ianstormtaylor/slate/pull/1202)
- [x] what do we do with footnotes?

#### Related issues
- [x] https://github.com/netlify/netlify-cms/issues/605 - can't edit data files
- [x] breaks sibling field updates when nested in a list as of https://github.com/netlify/netlify-cms/commit/c25a7c4abb76ed3ac041b18b86768fe94b70206f

### PR DESCRIPTION
**Pull request by erquhart**
Fixes a bunch of stuff on the new markdown editor. Related to #575, see issue for a list of bugs resolved.

### CODE REVIEW

**Comment by erquhart** [comment]
@Benaiah @tech4him1 @biilmann this is ready for review.

**Comment by erquhart** [comment]
I lied, adding more stuff.

**Comment by erquhart** [comment]
Actually I take that back. Let's get this into master as is, I'll add further fixes in a separate PR.

File: src/components/Widgets/Markdown/MarkdownControl/RawEditor/index.js [hunk 1]
```diff
@@ -22,16 +22,14 @@ export default class RawEditor extends React.Component {
...
   }
 
-  onChange = debounce(this.props.onChange, 250);
-
   /**
    * When the document value changes, serialize from Slate's AST back to plain
    * text (which is Markdown) and pass that up as the new value.
    */
-  handleDocumentChange = (doc, editorState) => {
+  handleDocumentChange = debounce((doc, editorState) => {
```
Comment (tech4him1) [inline src/components/Widgets/Markdown/MarkdownControl/RawEditor/index.js]: I haven't done that much on the editor stuff, but the debounce fix looks great! Thanks!

Comment (erquhart) [reply src/components/Widgets/Markdown/MarkdownControl/RawEditor/index.js]: Yeah it should help a lot with all of the heavy Immutable/React plumbing behind Slate. Night and day from the current editor on large docs.

File: src/components/Widgets/Markdown/serializers/slateRemark.js [hunk 2]
```diff
@@ -37,6 +38,108 @@ const markMap = {
   code: 'inlineCode',
 };
 
+let shortcodePlugins;
+
+export default function slateToRemark(raw, opts) {
+  /**
+   * Set shortcode plugins in outer scope.
+   */
+  ({ shortcodePlugins } = opts);
```
Comment (Benaiah) [inline src/components/Widgets/Markdown/serializers/slateRemark.js]: Instead of mutating a global variable, would it be possible to give an additional optional `shortcodePlugins` argument to  `transform` and curry it when `transform` recurses,
 e.g. `flatMap(combinedChildren, node => transform(node, shortcodePlugins))`? I don't see anything in this file preventing that, but the "mimics the approach of a Remark plugin" comment makes me wonder if this is getting used somewhere else that requires that single-argument API.

**Comment by erquhart** [comment]
@Benaiah I chose to leave some mutation in place to save time and because it might be more performant (crunching big docs is a bear in this editor). If all else is well let's leave these as is.

**Comment by Benaiah** [comment]
@erquhart sounds good to me, I'll approve and merge this.
