### PR TITLE
Fix large files failing to load.

### LINKED ISSUE #1092: Collections fail to load if any of the Github request is above 1mb
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Netlify CMS queries the Github API for files to add to its Collections. If any of those requests is above 1mb, Netlify CMS fails to render any of the other files.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Create a Markdown file above 1mb and notice how the Netlify CMS won't render any of the other files in a collection.

**- What is the expected behavior?**
In my opinion, Netlify CMS should be able to catch this error, display the file in a `disabled` state, and let the end user know why it was not able to load.

#### Note
The reason Netlify CMS cannot query files above 1mb is a Github API limitation. More info: https://developer.github.com/v3/repos/contents/#get-contents

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Fixes #1092. Allows files over 1MB to be fetched from GitHub's API.

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: src/backends/github/API.js [hunk 1]
```diff
@@ -156,21 +156,25 @@ export default class API {
   }
 
   readFile(path, sha, branch = this.branch) {
-    const cache = sha ? LocalForage.getItem(`gh.${ sha }`) : Promise.resolve(null);
-    return cache.then((cached) => {
-      if (cached) { return cached; }
+    if (sha) {
```
Comment (tech4him1) [inline src/backends/github/API.js]: @Benaiah I'm assuming if we know the SHA we should fetch by SHA first. Is that a problem at all?

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 2613a2c10c2bf84f55dba9706bd5a809c876a509

https://deploy-preview-1224--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 2613a2c10c2bf84f55dba9706bd5a809c876a509

https://deploy-preview-1224--cms-demo.netlify.com

File: src/backends/github/API.js [hunk 2]
```diff
@@ -156,18 +156,35 @@ export default class API {
   }
 
   readFile(path, sha, branch = this.branch) {
-    const cache = sha ? LocalForage.getItem(`gh.${ sha }`) : Promise.resolve(null);
-    return cache.then((cached) => {
-      if (cached) { return cached; }
-
+    if (sha) {
+      return this.getBlob(sha);
```
Comment (tech4him1) [inline src/backends/github/API.js]: Should we fetch the file by path if the SHA is invalid?

File: src/backends/github/API.js [hunk 3]
```diff
@@ -156,18 +156,35 @@ export default class API {
...
-      }).then((result) => {
-        if (sha) {
-          LocalForage.setItem(`gh.${ sha }`, result);
+      }).catch(error => {
+        if (hasIn(error, 'message.errors') && find(error.message.errors, { code:  "too_large" })) {
+          const dir = path.split('/').slice(0, -1).join('/');
+          return this.listFiles(dir)
+            .then(files => files.find(file => file.path === path))
+            // TODO: Should the case be handled where `file` is undefined? It should never happen because there is no pagination.
+            .then(file => getBlob(file.sha));
```
Comment (tech4him1) [inline src/backends/github/API.js]: Should the case be handled where `file` is undefined? It should never happen because there is no pagination.

File: src/backends/github/API.js [hunk 4]
```diff
@@ -156,18 +156,33 @@ export default class API {
...
         cache: "no-store",
-      }).then((result) => {
-        if (sha) {
-          LocalForage.setItem(`gh.${ sha }`, result);
+      }).catch(error => {
+        if (hasIn(error, 'message.errors') && find(error.message.errors, { code:  "too_large" })) {
+          const dir = path.split('/').slice(0, -1).join('/');
+          return this.listFiles(dir)
+            .then(files => files.find(file => file.path === path))
+            .then(file => getBlob(file.sha));
```
Comment (tech4him1) [inline src/backends/github/API.js]: Should the case be handled where `file` is undefined? It should never happen because there is no pagination.

File: src/backends/github/API.js [hunk 5]
```diff
@@ -156,18 +156,33 @@ export default class API {
   }
 
   readFile(path, sha, branch = this.branch) {
-    const cache = sha ? LocalForage.getItem(`gh.${ sha }`) : Promise.resolve(null);
-    return cache.then((cached) => {
-      if (cached) { return cached; }
-
+    if (sha) {
```
Comment (tech4him1) [inline src/backends/github/API.js]: @Benaiah I'm assuming if we know the SHA we should fetch by SHA first. Is that a problem at all?

File: src/backends/github/API.js [hunk 6]
```diff
@@ -156,18 +156,33 @@ export default class API {
...
         cache: "no-store",
-      }).then((result) => {
-        if (sha) {
-          LocalForage.setItem(`gh.${ sha }`, result);
+      }).catch(error => {
+        if (hasIn(error, 'message.errors') && find(error.message.errors, { code:  "too_large" })) {
+          const dir = path.split('/').slice(0, -1).join('/');
+          return this.listFiles(dir)
+            .then(files => files.find(file => file.path === path))
+            .then(file => this.getBlob(file.sha));
```
Comment (tech4him1) [inline src/backends/github/API.js]: Should the case be handled where `file` is undefined? It should never happen because there is no pagination.

File: src/backends/github/API.js [hunk 7]
```diff
@@ -156,18 +156,33 @@ export default class API {
...
+      });
+    }
+  }
+
+  getBlob(sha) {
+    return LocalForage.getItem(`gh.${sha}`).then(cached => {
+      if (cached) { return cached; }
+
+      return this.request(`${this.repoURL}/git/blobs/${sha}`, {
+        headers: { Accept: "application/vnd.github.VERSION.raw" },
```
Comment (erquhart) [inline src/backends/github/API.js]: We should be able to drop this header as it's only documented for use with the Contents API (unless you experienced an issue that required it).

File: src/backends/github/API.js (hunk 2 above)
Comment (erquhart) [reply src/backends/github/API.js]: Using the Contents API as a backup makes sense. I feel like there are edge cases like file name changes where this could cause confusion, but that seems pretty low risk.

File: src/backends/github/API.js (hunk 5 above)
Comment (erquhart) [reply src/backends/github/API.js]: Unless there's some benefit to using the Contents API, e.g. differences in the response object, fetching by SHA make sense to me.

File: src/backends/github/API.js (hunk 6 above)
Comment (erquhart) [reply src/backends/github/API.js]: Shouldn't happen, agreed.

File: src/backends/github/API.js (hunk 7 above)
Comment (tech4him1) [reply src/backends/github/API.js]: No, it is for use with the blobs API as well, see https://developer.github.com/v3/git/blobs/.

File: src/backends/github/API.js (hunk 2 above)
Comment (tech4him1) [reply src/backends/github/API.js]: I'll need to go back and check -- I'm assuming that we can just check for a 404?

Comment (tech4him1) [reply src/backends/github/API.js]: Although GitHub doesn't seem to ever do GC -- an invalid blob would be really weird. It would likely mean we were hashing the file differently than GitHub was on the server-side.

File: src/backends/github/API.js (hunk 7 above)
Comment (erquhart) [reply src/backends/github/API.js]: Ah, I see it now 👍
