### PR TITLE
escape markdown entities entered as literal text

### LINKED ISSUE #558: markdown characters not escaped in new editor
**- Do you want to request a *feature* or report a *bug*?**
bug, caused by #254 

**- What is the current behavior?**
If a user types (#) pound character(s) at the beginning of a line in the regular editor, then switches to the markdown editor (and edits anything), the editor will convert the line to a heading.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. In the regular editor, add a line like this: `## this is a test`.
2. Switch to the markdown editor and change any line (doesn't have to be the same line).

**- What is the expected behavior?**
The pound sign should be escaped, like in the old editor (`\## this is a test`).
**We should probably check all other special MD characters as well.**

### PR DESCRIPTION
**Pull request by erquhart**
**- Summary**

When markdown entities are entered in the visual editor, they are not escaped in the underlying markdown, which results in the entities being unintentionally parsed as raw markdown.

Closes #558.

**- Test plan**

Tested in the editor, provided unit tests.

**- Description for the changelog**

- escape markdown entities entered as literal text

**- A picture of a cute animal (not mandatory but encouraged)**
047ab429558ecc877aa255d1f8e6a8d8--funny-animal-pictures-animals

### CODE REVIEW

File: src/components/Widgets/Markdown/serializers/index.js [hunk 1]
```diff
@@ -164,10 +165,30 @@ export const remarkToMarkdown = obj => {
...
 
+  const remarkToMarkdownPluginOpts = {
+    commonmark: true,
+    fences: true,
+    pedantic: true,
+    listItemIndent: '1',
+
+    // Settings to emulate the defaults from the Prosemirror editor, not
+    // necessarily optimal. Should eventually be configurable.
+    bullet: '*',
```
Comment (tech4him1) [inline src/components/Widgets/Markdown/serializers/index.js]: This doesn't affect how it is read, right? just how we write it?

File: src/components/Widgets/Markdown/serializers/remarkEscapeMarkdownEntities.js [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+    return text.replace(/[\[*_`~]/g, '\\$&');
+  }
+
+  /**
+   * Runs escapeCommonChars, and also escapes '#' and '-' when found at the
+   * beginning of any node's first child node.
+   */
+  function escapeAllChars(text) {
+    const partiallyEscapedMarkdown = escapeCommonChars(text);
+    return partiallyEscapedMarkdown.replace(/^\s*([#-])/, '$`\\$1');
```
Comment (tech4him1) [inline src/components/Widgets/Markdown/serializers/remarkEscapeMarkdownEntities.js]: This works fine, but I almost wonder if it would be simpler just to replace all characters all the time, just to avoid edge cases. Either way I'm fine with it.

File: src/components/Widgets/Markdown/serializers/index.js [hunk 3]
```diff
@@ -164,10 +165,30 @@ export const remarkToMarkdown = obj => {
...
+    strong: '*',
+    rule: '-',
+  };
+
+  /**
+   * Escape markdown entities found in text and html nodes within the MDAST.
+   */
+  const escapedMdast = unified()
+    .use(remarkEscapeMarkdownEntities)
+    .runSync(mdast);
```
Comment (tech4him1) [inline src/components/Widgets/Markdown/serializers/index.js]: I don't understand how this actually works, just because I'm not familiar with ReMark, but it looks fine to me.

File: src/components/Widgets/Markdown/serializers/remarkEscapeMarkdownEntities.js (hunk 2 above)
Comment (Benaiah) [reply src/components/Widgets/Markdown/serializers/remarkEscapeMarkdownEntities.js]: I'd prefer to leave the markdown as human-editable as possible and address edge cases as they occur.

File: src/components/Widgets/Markdown/serializers/index.js (hunk 1 above)
Comment (erquhart) [reply src/components/Widgets/Markdown/serializers/index.js]: Right, once markdown is transformed to AST, there's no record of which character was used for things like bullets. This sets which character to use when stringifying back to markdown, which happens when switching from visual editor to markdown mode, and also when saving the entry.

File: src/components/Widgets/Markdown/serializers/remarkEscapeMarkdownEntities.js (hunk 2 above)
Comment (erquhart) [reply src/components/Widgets/Markdown/serializers/remarkEscapeMarkdownEntities.js]: @tech4him1 keep in mind that any markdown entity in the raw editor that isn't active, e.g. a lone asterisk, will be escaped when the markdown is stringified. In other words, the user enters an asterisk in the raw editor, they save the entry, then they re-open and it's been escaped. To some extent it has to be that way, but we want to minimize occurrences of unexpected transformation.

This is an edge case, as Benaiah mentioned, that we want to tackle. These two characters are benign unless they are at the beginning of a line, so there's no need to escape them at any other time. As bug reports come on we'll probably be extending this plugin to handle more edge cases.

File: src/components/Widgets/Markdown/serializers/index.js (hunk 3 above)
Comment (erquhart) [reply src/components/Widgets/Markdown/serializers/index.js]: Yeah, basically remark/unified lets you run parsers via `.parse()`, plugins via `.run()/.runSync()`, stringifiers via `.stringify()`, or all three together via `.process()/.processSync()`. Because of our use case, we never run all three together.

What I've done here is applied a plugin (synchronous, no need for async here) to the MDAST (MarkDown AST). The plugin is passed the entire tree, and it recursively transforms the contents of text nodes by escaping markdown entities.
