### PR TITLE
Fix #458 by ending case sensitivity of names of fields used in slug construction

### LINKED ISSUE #458: silent failure on save due to case of collection "Title" in config.yml
I tested on cms.js v 4.2 and v3.22 in both latest safari and chrome.

Saving always failed (silently).  Looking in console I got:

screen shot 2017-06-17 at 5 18 55 pm

Appears to be in:

```javascript
const slugFormatter = (template = "{{slug}}", entryData) => {
  const date = new Date();
  const identifier = entryData.get("title", entryData.get("path"));  <---- NULL
  return template.replace(/\{\{([^\}]+)\}\}/g, (_, field) => {
    switch (field) {
      case "year":
        return date.getFullYear();
      case "month":
        return (`0${ date.getMonth() + 1 }`).slice(-2);
      case "day":
        return (`0${ date.getDate() }`).slice(-2);
      case "slug":
        return slug(identifier.trim(), {lower: true});  <---- EXPLODE HERE
      default:
        return slug(entryData.get(field, "").trim(), {lower: true});
    }
  });
```

because my `config.yml` has this

```yaml
    fields:
      - {label: "Title", name: "Title", widget: "string"}
```

i.e.  `name: Title` not `name: title`

Seems like this could be made more robust or more clear on what failed.

thanks,

n

### PR DESCRIPTION
**Pull request by eamonnbell**
**- Summary**

`identifier` is used to build slug when slug field is `{{slug}}` and was retrieved using nested `.get()` methods on `entryData` which did not fail gracefully and was sensitive to the case of the field name declaration in `config.yml` This change makes the assignment of `identifier` more robust by making it effectively case-insensitive, by throwing a meaningful error when no usable entry identifier can be found, and by moving the   assignment of `identifier` inside the `case "slug"` so that it is only assigned when required.

**- Test plan**

Tested using steps to repro in #458 on Chromium using test-repo backend. 

All jest tests passing.

**- Description for the changelog**

Names of entry fields used in slug construction as entry identifiers are no longer case-sensitive

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

File: src/backends/backend.js [hunk 1]
```diff
@@ -26,7 +26,24 @@ class LocalStorageAuthStore {
 
 const slugFormatter = (template = "{{slug}}", entryData) => {
   const date = new Date();
-  const identifier = entryData.get("title", entryData.get("path"));
+
+  const getIdentifier = (entryData) => {
```
Comment (Benaiah) [inline src/backends/backend.js]: We should probably call `.trim` on `entryData` *before* we check it against the list of valid identifiers, rather than in [line 56](https://github.com/netlify/netlify-cms/pull/460/files#diff-bb12caf37386494eb84dc9a5aca4abe1R56), so we don't reject field names based on spurious whitespace.

File: src/backends/backend.js [hunk 2]
```diff
@@ -26,7 +26,24 @@ class LocalStorageAuthStore {
...
+	  const validIdentifierFields = ["title", "path"];
+	  const identifiers = validIdentifierFields.map((field) => {
+	  	return entryData.find((_, key) => {
+	  		return key.toLowerCase() === field;
```
Comment (Benaiah) [inline src/backends/backend.js]: The braces and `return` keywords are unnecessary - this can be rewritten identically like so:

```js
const identifiers = validIdentifierFields.map((field) =>
  entryData.find((_, key) => key.toLowerCase() === field)
);
```

File: src/backends/backend.js [hunk 3]
```diff
@@ -26,7 +26,24 @@ class LocalStorageAuthStore {
...
+	  	});
+	  });
+	  
+	  const identifier = identifiers.find(i => typeof i !== 'undefined');
+
+	  if (typeof identifier === 'undefined') {
```
Comment (Benaiah) [inline src/backends/backend.js]: `Array.find` always returns `undefined` when it doesn't match (per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find), and `undefined` always `=== undefined`, so this comparison can be changed to the simpler `identifier === undefined` (`identifier` is always a defined variable, which is what the `typeof identifier === undefined` would normally be used to detect).

File: src/backends/backend.js [hunk 4]
```diff
@@ -26,7 +26,24 @@ class LocalStorageAuthStore {
...
+	      throw new Error("Collection must have a field name that is a valid entry identifier"); 
+	  } else {
```
Comment (Benaiah) [inline src/backends/backend.js]: There's no need for this `else`, as execution will not proceed pass the `if` block if the condition is true. Instead, you can just `return identifier;` at the end of the function.

File: src/backends/backend.js [hunk 5]
```diff
@@ -36,7 +53,7 @@ const slugFormatter = (template = "{{slug}}", entryData) => {
       case "day":
         return (`0${ date.getDate() }`).slice(-2);
       case "slug":
-        return slug(identifier.trim(), {lower: true});
+        return slug(getIdentifier(entryData).trim(), {lower: true});
```
Comment (Benaiah) [inline src/backends/backend.js]: See above comment regarding this `.trim()` call.

File: src/backends/backend.js [hunk 6]
```diff
@@ -26,7 +26,24 @@ class LocalStorageAuthStore {
...
+
+  const getIdentifier = (entryData) => {
+	  const validIdentifierFields = ["title", "path"];
+	  const identifiers = validIdentifierFields.map((field) => {
+	  	return entryData.find((_, key) => {
+	  		return key.toLowerCase() === field;
+	  	});
+	  });
+	  
+	  const identifier = identifiers.find(i => typeof i !== 'undefined');
```
Comment (Benaiah) [inline src/backends/backend.js]: Please don't use the single-letter variable `i` to mean anything except a loop index. `ident` might be a good replacement here. `typeof i !== 'undefined'` can also be replaced with either `i === undefined` (exactly equivalent to what you have here, and more readable) or `_.isNil` from lodash (will also catch `null` values) - the `typeof` is unnecessary.

**Comment by erquhart** [comment]
@eamonnbell thanks for this! Looks like Benaiah provided a review, so just a few changes and we can get this merged. Nice pun on the slug pic, too lol.

File: src/backends/backend.js (hunk 1 above)
Comment (eamonnbell) [inline src/backends/backend.js]: Agreed. Commit e51071a implements this behavior. 

I think the original calls in L56 to `.trim` are to trim the value corresponding to the field so that it doesn't mess up the slug, not the field itself (the key).

**Comment by eamonnbell** [comment]
Thanks for the detailed and helpful review, @Benaiah.

I have made the changes you requested in the commits above. I kept--instead of moving--the calls to `trim` on the values passed to `slug` (see my reply to your code comment). Let me know if my thinking is wrong there.

**Comment by eamonnbell** [comment]
Merging. Thanks again, all.
