### PR TITLE
fix: Remove `Unpublish` UI button if  collection has a `delete: false`. (#3887)

### LINKED ISSUE #3887: Unpublish is visible for collections with disabled delete
**Describe the bug**
When editorial workflow is enabled and a collection has `delete: false` the editor is still able to "unpublish" the entry, which essentially does a delete.

**To Reproduce**
1. Enable the editorial workflow
2. Set `delete: false` for a collection
3. Edit an entry in the same collection
4. See that there is an `Unpublish` option in the publish menu

**Expected behavior**
The editor should not see the `Unpublish` menu item.

### PR DESCRIPTION
**Pull request by AbdallahAbis**
Closes #3887 

**Summary**
This PR aims to hide the `unpublish` button in the UI when a collection has a `delete: false` flag, Since netlify prevents the `unpublish` action in the backend when `!delete` then it's a good idea to hide the button from the UI in the first place.

Before: 
Screen Shot 2021-04-28 at 12 49 32

After:
Screen Shot 2021-04-28 at 12 50 02

**Test plan**
I couldn't find a way to test this.

**A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

File: packages/netlify-cms-core/src/components/Editor/EditorToolbar.js [hunk 1]
```diff
@@ -393,7 +393,7 @@ class EditorToolbar extends React.Component {
           </PublishedToolbarButton>
         )}
       >
-        {canPublish && (
+        {(!canNotDelete && canPublish) && (
```
Comment (erezrokah) [inline packages/netlify-cms-core/src/components/Editor/EditorToolbar.js:396]: Can we rename this to `canDelete` and avoid the negation?

I think `const canDelete = collection.get('delete', true)` should work

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thanks @AbdallahAbis,

I have a small suggestion before we think about testing this.

**Review by erezrokah — APPROVED** [review]
Thanks @AbdallahAbis!
