### PR TITLE
Fixes #298 Basic validation for config

### LINKED ISSUE #298: Need a Better error when missing Collections in the config.yml
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When someone sets up a project with the CMS and does not set up 

**- If the current behavior is a bug, please provide the steps to reproduce.**
Open the example add in this Repo, or start a new project without adding a `collection` to the config.yml and begin to weep at the unintelligible error message.

```
Uncaught (in promise) TypeError: Cannot read property 'replaceChild' of null" [...] 
```

**- What is the expected behavior?**
Return a better error message that tells the user they need a collection in the config.yml

example: https://github.com/simonhermann/mx-jekyll/blob/472dcadac9993e0fc6fab73e583c3ec013d6bb67/admin/config.yml

### PR DESCRIPTION
**Pull request by josephearl**
**- Summary**

Fixes #298 - adds some basic validation for the config.

**- Test plan**

Added some unit tests for config validations.

screen shot 2017-04-14 at 22 34 42
screen shot 2017-04-14 at 22 34 17
screen shot 2017-04-14 at 22 34 28

**- Description for the changelog**

Add a `validateConfig` to provide basic validation of configuration.

**- A picture of a cute animal (not mandatory but encouraged)**

Cute polar bear on it's back

### CODE REVIEW

File: src/actions/config.js [hunk 1]
```diff
@@ -24,21 +20,41 @@ export function applyDefaults(config) {
   return defaultsDeep(config, defaults);
 }
 
+export function validateConfig(config) {
+  if (!has(config, 'backend' || !config['backend'])) {
```
Comment (erquhart) [inline src/actions/config.js]: I think the first closing parens is misplaced here.

You can shorten this and a few of the following conditions using `lodash.get` in the form of:

`if (!get(config, 'backend'))`

-or-

`if (!get(config, ['backend', 'name']))`

File: src/actions/config.js [hunk 2]
```diff
@@ -24,21 +20,41 @@ export function applyDefaults(config) {
...
+    throw new Error("Error in configuration file: A `backend` wasn't found. Check your config.yml file.");
+  }
+  if (!has(config['backend'], 'name') || !config['backend']['name']) {
+    throw new Error("Error in configuration file: A `backend.name` wasn't found. Check your config.yml file.");
+  }
+  if (typeof config['backend']['name'] !== 'string') {
```
Comment (erquhart) [inline src/actions/config.js]: Just use dot notation if you have the property name.

File: src/actions/config.js (hunk 1 above)
Comment (josephearl) [inline src/actions/config.js]: Thanks for the pointer - simplified things quite a bit

File: src/actions/config.js (hunk 2 above)
Comment (josephearl) [inline src/actions/config.js]: Fixed

**Comment by josephearl** [comment]
Thanks for the review, updated

**Comment by calavera** [comment]
LGTM

File: src/actions/config.js [hunk 3]
```diff
@@ -1,5 +1,5 @@
 import yaml from "js-yaml";
-import { set, defaultsDeep } from "lodash";
+import { set, defaultsDeep, has, get } from "lodash";
```
Comment (erquhart) [inline src/actions/config.js]: Remove the `has` import.

Comment (josephearl) [inline src/actions/config.js]: Good catch

**Comment by josephearl** [comment]
Removed unused `has` import
