### PR TITLE
Flash an error on save when required fields are missed

### LINKED ISSUE #649: Saving fails *almost* silently when required fields are left empty
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
If a user tries to save an item with an empty required field, the save button appears to do nothing at all. If you look closely (and aren't color blind), you may notice that one or more field labels have turned red. This is the only indication of why saving fails, and it can be really easy to miss, especially if the fields in question are offscreen.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a new post on [cms-demo](https://cms-demo.netlify.com/#/collections/posts/entries/new). (<--That link will take you straight to the new post page.)
2. Without adding any content, click Save.
3. See that Title and Body labels turn red, but no other feedback is given.

**- What is the expected behavior?**
At minimum, a general error message that says something like, "Oops, you've missed a required field. Please complete before saving." It would also be helpful to have a more noticeable, accessible indicator on the offending fields.

**- Please mention your CMS, node.js, and operating system version.**
True on all versions I know of, in any browser.

### PR DESCRIPTION
**Pull request by aquibm**
**- Summary**
 - Fixes #649
 - Flash an error message when the user saves without completing all required fields
 - Surface presence errors on required fields

**- Test plan**
 - Attempting to save without completing all required fields should flash the new error.
 - Should display `[FieldName] is required` in the list of errors for fields that are required and not filled in.
 - Demo: [https://streamable.com/ik5n5](https://streamable.com/ik5n5)

**- Description for the changelog**
 Add an error message to notify the user about missed required fields when saving.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: src/actions/entries.js [hunk 1]
```diff
@@ -265,9 +266,23 @@ export function persistEntry(collection) {
   return (dispatch, getState) => {
     const state = getState();
     const entryDraft = state.entryDraft;
+    const fieldsErrors = entryDraft.get('fieldsErrors');
 
     // Early return if draft contains validation errors
-    if (!entryDraft.get('fieldsErrors').isEmpty()) return Promise.reject();
+    if (!fieldsErrors.isEmpty()) {
+      const hasPresenceErrors = fieldsErrors
+        .some(errors => errors.some(error => error.type && error.type === ValidationErrorTypes.PRESENCE));
```
Comment (tech4him1) [inline src/actions/entries.js]: Is there a reason we only check for `PRESENCE` errors here, instead of all the kind of Validation errors? That's obviously the actual issue request, but why not make a popup for pattern or custom errors as well?

CC/ @erquhart

Comment (aquibm) [reply src/actions/entries.js]: I [originally had it working this way](https://streamable.com/2evve) as it was a lot easier than introducing types for the different errors and interrogating errors based on type when saving.

I'm happy with either approach but have a slight preference towards the original as it both addresses the issue by identifying required fields that failed validation and is a much smaller change. 👍
