### PR TITLE
fix: ensure draft changes

### LINKED ISSUE #3256: CMS creates an empty branch and PR
**Describe the bug**
When I save page where is no edits editorial_workflow creates an empty branch and PR in bitbucket repo. 
And seems because of this CMS fails with error msg:
Failed to load entry: TypeError: Cannot destructure property 'newPath' of 'o.find(...)' as it is undefined.

Steps to reproduce:
1. Open any page
2. Add a any data to some input
3. Remove this data, to have the same state as it was before your edits
4. Save button is now available, click Save
5. CMS creates empty Branch with empty PR in bitbucket repo
6. CMS shows error and fails to work

Image:
https://monosnap.com/file/bhi3w4LPqc48kXWpurMaiVKtit9AVn

**Expected behavior**
No error msg, CMS working fine

**Screenshots**
https://monosnap.com/file/bhi3w4LPqc48kXWpurMaiVKtit9AVn

**Applicable Versions:**
 - netlify-cms-app 2.11.16, netlify-cms-core 2.18.1(with manual init)
 - Git provider: BitBucket
 - OS: MacOS
 - Chrome Version 80.0.3987.100 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by barthc**
Closes #3256

Now that we are using the `diff` API to pull workflow changes, it makes sense to make sure that they are actual draft changes before saving by comparing the current entry draft with unpublished or published Entry.

The changes also take care of the `relation` widget unsaved changes bug  #725.

### CODE REVIEW

**Comment by erezrokah** [comment]
I like the approach in this PR, will try to finalize the review soon.

**Comment by erezrokah** [comment]
Realized this is similar to https://github.com/netlify/netlify-cms/pull/3305, will go over both of them

**Comment by erezrokah** [comment]
I'm still able to reproduce the bug on https://bitbucket.org/erezro/netlify-cms-reproductions/branch/netlify_cms/issue_3256:
no_diff_bug


PR: https://bitbucket.org/erezro/netlify-cms-reproductions/pull-requests/5/update-post-test/diff

**Comment by erezrokah** [comment]
Seems to be related to https://github.com/jonschlinkert/gray-matter/issues/96.
A new line is always added at the end of the file here:
https://github.com/netlify/netlify-cms/blob/53365b73701c872948a1e65da00a655e0718e8cb/packages/netlify-cms-core/src/formats/frontmatter.js#L87

**Comment by barthc** [comment]
I think it's the `markdown` widget, the rich text mode is inserting a tab at the beginning of the string on edit. But the markdown mode is good.

**Comment by erezrokah** [comment]
Can you share a way to get that tab inserted? I couldn't reproduce it.

I was able to fix my issue by removing the extra line break inserted by `gray-matter`.
See here https://github.com/netlify/netlify-cms/commit/411d9860fd283b224418b1617a6464fb851e6e1c.

This might have some non-intuitive results as our markdown widget seems to strip line breaks at the end. Notice in the following GIF, it won't report a change until a non line break character is inserted:
gray_matter_line_breaks

**Comment by barthc** [comment]
Here is the markdown mode:

Peek 2019-11-24 23-57

File: packages/netlify-cms-core/src/reducers/entryDraft.js [hunk 1]
```diff
@@ -88,13 +88,22 @@ const entryDraftReducer = (state = Map(), action) => {
...
         state.mergeDeepIn(['fieldsMetaData'], fromJS(action.payload.metadata));
         state.set('hasChanged', true);
       });
+      const newStateData = newState.getIn(['entry', 'data']);
+
+      (newStateData.equals(unpublishedEntry.get('data')) ||
+        newStateData.equals(publishedEntry.get('data'))) &&
+        (newState = newState.set('hasChanged', false));
 
+      return newState;
```
Comment (bharrisau) [inline packages/netlify-cms-core/src/reducers/entryDraft.js]: Can this be done with only a single Immutable node?

```
return state.withMutations(state => {
  state.setIn(['entry', 'data', action.payload.field], action.payload.value);
  state.mergeDeepIn(['fieldsMetaData'], fromJS(action.payload.metadata));

  const newData = state.getIn(['entry', 'data']);
  const matchesLastSaved = newData.equals(unpublishedEntry.get('data')) || newData.equals(publishedEntry.get('data'))
 
  state.set('hasChanged', !matchesLastSaved);
});

Comment (erezrokah) [reply packages/netlify-cms-core/src/reducers/entryDraft.js]: I changed that in my branch https://github.com/netlify/netlify-cms/commit/411d9860fd283b224418b1617a6464fb851e6e1c#diff-9409717c5b67d95c17fad5f0b8165dd8R106

**Comment by bharrisau** [comment]
Couple of comments/questions
- Is `.equals` going to give the expected equality when matching maps? Immutable provides `.is` that gives good deep matching, but I'm only a flythrough contributor so I'm not clear enough on the codebase to know if `.equals` will do the same.
- Is it worth adding a test spec for this behavior?
- Is it possible to consolidate `unpublishedEntry` and `publishedEntry` into just the one `lastSavedEntry` or something? I'm not clear on why there are two possible states that can set `hasChanged` to false. As a user, there would only be one last saved version of the document right? so only one state that would remove the save button?

**Comment by bharrisau** [comment]
I prefer this approach over the simple mod I proposed in #3305 - this looks like if you change something and then change it back it would recognize that the data matches the previous version.

**Comment by barthc** [comment]
> Is it possible to consolidate unpublishedEntry and publishedEntry into just the one lastSavedEntry or something? I'm not clear on why there are two possible states that can set hasChanged to false. As a user, there would only be one last saved version of the document right? so only one state that would remove the save button?

It has to compare both entries, for example, if a user makes workflow changes and on subquest edits revert the workflow changes back to the published entry, we will still have the diff issue,

**Comment by bharrisau** [comment]
> > Is it possible to consolidate unpublishedEntry and publishedEntry into just the one lastSavedEntry or something? I'm not clear on why there are two possible states that can set hasChanged to false. As a user, there would only be one last saved version of the document right? so only one state that would remove the save button?
> 
> It has to compare both entries, for example, if a user makes workflow changes and on subquest edits revert the workflow changes back to the published entry, we will still have the diff issue,

Might be a silly question (again, not familiar with the codebase) - but can picking between those two be the responsibility of the `Editor.js` when it is calling `changeDraftField`?

Alternatively, can you just pass through an array of entries that should be compared against? `[unpublishedEntry, publishedEntry].filter(remove nulls)`
Then the reducer API wouldn't need to be changed in the future if there were more states to compare against?

Probably bikeshedding now - but I see APIs where multiple fields are treated identically and I start asking if there needs to be multiple fields.

**Comment by erezrokah** [comment]
> our markdown widget seems to strip line breaks

This happens [here](https://github.com/netlify/netlify-cms/blob/53365b73701c872948a1e65da00a655e0718e8cb/packages/netlify-cms-widget-markdown/src/serializers/index.js#L145). Tried removing it, but create other issues when parsing loading the saved markdown.

**Comment by barthc** [comment]
> Alternatively, can you just pass through an array of entries that should be compared against? [unpublishedEntry, publishedEntry].filter(remove nulls)
Then the reducer API wouldn't need to be changed in the future if there were more states to compare against?

So the possible values for `unpublishedEntry, publishedEntry` at any time could be empty 'Map()` for both, one empty and the other with some value, and then both have values.

**Comment by barthc** [comment]
> Is .equals going to give the expected equality when matching maps? Immutable provides .is that gives good deep matching, but I'm only a flythrough contributor so I'm not clear enough on the codebase to know if .equals will do the same.

Looks like `equals` is calling `is` under the hood https://immutable-js.github.io/immutable-js/docs/#/Collection/equals

**Comment by bharrisau** [comment]
> Looks like `equals` is calling `is` under the hood https://immutable-js.github.io/immutable-js/docs/#/Collection/equals

No worries. And don't feel like you need to change anything above (unpublished/published) - I just make comments about possible alternatives in reviews because that's how I like others to review my stuff.

**Comment by barthc** [comment]
@erezrokah  any luck with the `markdown`  ?

**Comment by erezrokah** [comment]
Not yet and we might want to handle those issues in another PR.
We should at least make sure `gray-matter` doesn't add that line break as at the moment it seems we will always add it on save, but never report it in the value of the change event.
I'll keep looking

File: packages/netlify-cms-core/src/formats/frontmatter.js [hunk 2]
```diff
@@ -72,7 +72,7 @@ class FrontmatterFormatter {
     const result = matter(content, { engines: parsers, ...format });
     return {
       ...result.data,
-      body: result.content,
+      ...(result.content.trim() && { body: result.content }),
```
Comment (erezrokah) [inline packages/netlify-cms-core/src/formats/frontmatter.js]: @barthc do you mind sharing the reason this is required?

Comment (barthc) [reply packages/netlify-cms-core/src/formats/frontmatter.js]: It's the same line break issue at the end of the file. So when the file is parsed, it includes a `body` key with line break as value, this would occur for config fields without the top-level markdown body widget that resolves to the body of the markdown.

Comment (erezrokah) [reply packages/netlify-cms-core/src/formats/frontmatter.js]: Thanks I think I get it now.
We pass in an empty body here:
https://github.com/netlify/netlify-cms/blob/3e873f3e0277bca8f5dee619e931a66d47779c3d/packages/netlify-cms-core/src/formats/frontmatter.js#L80

when it doesn't exist, so we have to remove that property on parse.

**Comment by erezrokah** [comment]
@barthc are you good with me adding the other line break fix (https://github.com/netlify/netlify-cms/commit/411d9860fd283b224418b1617a6464fb851e6e1c#diff-ac1a295de180688364c35e08b03a343fR89)?

We can fix the behaviour in https://github.com/netlify/netlify-cms/pull/3306#issuecomment-591331445 in another PR.
#3256 and #725 seem more important to have fixed.

WDYT?

**Comment by barthc** [comment]
Yes please do, thanks.

**Comment by erezrokah** [comment]
looking into the tests failures
