### PR TITLE
Filter merged PRs from unpublished posts

### LINKED ISSUE #251: Bug: Merging PR in GitHub without deleting branch causes trouble
If a CMS generated PR gets merged through GitHub without deleting the CMS branch, the editorial workflow keeps the card, but any attempt at publishing it fails.

### PR DESCRIPTION
**Pull request by Benaiah**
**- Summary**

Don't show posts which have been merged outside of the CMS as unpublished posts in the editorial workflow.

Closes #251.

**- Test plan**

Manually tested.

**- Description for the changelog**

- **Filter merged PRs from unpublished posts**

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

File: src/backends/github/API.js [hunk 1]
```diff
@@ -174,9 +175,23 @@ export default class API {
...
+
     return this.request(`${ this.repoURL }/git/refs/heads/cms`)
+    .then(branches => filterPromises(branches, (branch) => {
+      const branchName = branch.ref.substring("/refs/heads/".length - 1);
+
+      // Get PRs with a `head` of `branchName`. Note that this is a
+      // substring match, so we need to check that the `head.ref` of
+      // at least one of the returned objects matches `branchName`.
+      return this.request(`${ this.repoURL }/pulls?head=${ branchName }&state=open`)
+        .then(prs => prs.reduce((exists, pr) => exists || pr.head.ref === branchName, false));
```
Comment (erquhart) [inline src/backends/github/API.js]: Consider using `prs.some` instead of `prs.reduce`, more self-documenting that way, and a tad shorter.

File: src/backends/github/API.js [hunk 2]
```diff
@@ -174,9 +175,23 @@ export default class API {
     return unpublishedPromise;
   }
 
+  buildUnpublishedPRSearchQuery(branch) {
```
Comment (erquhart) [inline src/backends/github/API.js]: Any reason not to remove this?

File: src/backends/github/API.js [hunk 3]
```diff
@@ -1,6 +1,7 @@
 import LocalForage from "localforage";
 import { Base64 } from "js-base64";
 import _ from "lodash";
+import { filterPromises, reducePromises } from "../../lib/promiseHelper";
```
Comment (erquhart) [inline src/backends/github/API.js]: `reducePromises` should be removed, left over from the original PR I assume.

**Comment by erquhart** [comment]
@Benaiah just a few changes requested and we can merge.

File: src/backends/github/API.js (hunk 2 above)
Comment (Benaiah) [inline src/backends/github/API.js]: This is leftover from an earlier implementation - thanks for catching it.

File: src/backends/github/API.js (hunk 3 above)
Comment (Benaiah) [inline src/backends/github/API.js]: Ditto.

**Comment by Benaiah** [comment]
@erquhart thanks for the review; I've addressed your comments.
