### PR TITLE
fix(typing): add `registerEventListener` to CMS interface

### LINKED ISSUE #4782: missing type: registerEventListener in netlify-cms-core
**Describe the bug**

while trying to use CMS Events via (/cms/cms.js) in my gatsby project:

```
import CMS from 'netlify-cms-app'
import BlogPostPreview from './preview-templates/BlogPostPreview'
import { de } from 'netlify-cms-locales';

CMS.registerPreviewTemplate('blog', BlogPostPreview)
CMS.registerLocale('de', de);

CMS.registerEventListener({
  name: 'prePublish', // or preSave
  handler: ({ entry }) => {
    console.log(entry);
  }
})
```

I saw that **registerEventListener** is not part of the TS typings in netlify-cms-core as opposed to other methods like the ones i used before the registerEvent call. Furthermore it seems i cant even register the listener. No console output fired.

**Expected behavior**
some console logging on publishing an entry in the CMS UI.

**Applicable Versions:**
netlify-cms-app 2.14.8
netlify-cms-core 2.36.7

 - Git provider:  GitHub

### PR DESCRIPTION
**Pull request by hkennyv**
fixes #4782

this is my first contribution, would love to get some review on it. i can open a code review on the specific points

**Summary**

adds `registerEventListener` to CMS interface in netlify-cms-core

**Test plan**

`yarn test` output (truncated):

```
Test Suites: 2 skipped, 73 passed, 73 of 75 total
Tests:       650 skipped, 922 passed, 1572 total
Snapshots:   89 passed, 89 total
Time:        27.788 s
Ran all test suites.
✨  Done in 56.91s.
```

**A picture of a cute animal (not mandatory but encouraged)**

7301D0F6-33E2-4078-AEC4-404CA828B9A0

my cat, winston :)

### CODE REVIEW

File: packages/netlify-cms-core/index.d.ts [hunk 1]
```diff
@@ -403,6 +404,13 @@ declare module 'netlify-cms-core' {
     config?: CmsMediaLibraryOptions;
   }
 
+  export interface CmsEventListener {
+    name: string;
```
Comment (erezrokah) [inline packages/netlify-cms-core/index.d.ts:408]: Should we limit the `name` the to list of allowed events?
https://github.com/netlify/netlify-cms/blob/567438fdd1aa775fd09a6a5de13e79c9d783e0d6/packages/netlify-cms-core/src/lib/registry.js#L6

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thanks @hkennyv, looks great. Just a small suggestion
