### PR TITLE
Fixes #3807 by ensuring we don't attempt to split an empty string.

### LINKED ISSUE #3807: Removing all values from the list with empty array as default value results in array of one empty string
**Describe the bug**
When list widget has empty array as default value, removing all values from it results in array of one empty string

**To Reproduce**
```yaml
  - label: Posts
    label_singular: post
    name: post
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Tags, name: tags, widget: list, allow_add: true, required: false, default: []}
      - {label: Body, name: body, widget: markdown}
```
1. Create new post
2. Don't fill the tags input
3. Publish post
4. Check the data
```md
---
title: Test
tags: []
---
test
``` 
5. Edit post by adding one tag
6. Publish and check the data
```md
---
title: Test
tags:
 - tag
---
test
``` 
5. Edit post by removing this tag
6. Publish and check the data
```md
---
title: Test
tags:
 - ""
---
test
``` 

**Expected behavior**
After removing all tags data should be the following
```md
---
title: Test
tags: []
---
test
```

### PR DESCRIPTION
**Pull request by annafoldvari**
**Summary**

Fixes #3807 ("Removing all values from the list with empty array as default value results in array of one empty string")

As per issue #3807 , the Widget List would save an array with an empty string when attempting to delete all elements from the widget.

The source of the problem is that splitting an empty string in Javascript returns an array with an empty string - this is as the language is designed, see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

**Test plan**

I ran `yarn test` and `yarn format`.

**A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

File: packages/netlify-cms-widget-list/src/ListControl.js [hunk 1]
```diff
@@ -155,7 +155,10 @@ export default class ListControl extends React.Component {
     const { onChange } = this.props;
     const oldValue = this.state.value;
     const newValue = e.target.value;
-    const listValue = e.target.value.split(',');
+    let listValue = [];
+    if (e.target.value.trim().length > 0) {
```
Comment (smashercosmo) [inline packages/netlify-cms-widget-list/src/ListControl.js:159]: why not reuse newValue variable?

Comment (smashercosmo) [reply packages/netlify-cms-widget-list/src/ListControl.js:159]: Also, seems that it can be simplified to
```js
const newValue = e.target.value.trim()
const listValue = newValue ? newValue.split(',') : []
```
because newValue should always be a string

Comment (annafoldvari) [reply packages/netlify-cms-widget-list/src/ListControl.js]: Thanks for the comment. Changes have been applied as suggested.

**Review by erezrokah — APPROVED** [review]
Thanks @annafoldvari, nice one :)
