### PR TITLE
fix(core): number type slug template

### LINKED ISSUE #2118: Number type is not supported in slug template
**Describe the bug**
I am trying to create new file with order suffix after slug. I get the error "r.get().trim is not a function" when save new document. I think number type is not supported

**Screenshots**

image

**Applicable Versions:**
 - Netlify CMS version: 2.4
 - Git provider: GitHub
 - OS: Ubuntu 18.04
 - Browser version:72.0.3626.96 (Official Build) (64-bit)

**CMS configuration**
```
identifier_field: "name"
    slug: "{{slug}}_{{order}}"
    fields:
      - label: "Id"
        name: "id"
        hint: "Referencing id"
        pattern: ['^\w+$', "Only alphanumeric and _ characters"]

      - label: "Name"
        name: "name"
        hint: "Display name"
        widget: "string"

      - label: "Order"
        name: "order"
        hint: "Order of the section on the side navigation menu"
        widget: "number"
        min: 0
        max: 100
```

### PR DESCRIPTION
**Pull request by barthc**
**Summary**

Closes #2118

### CODE REVIEW

File: packages/netlify-cms-core/src/backend.js [hunk 1]
```diff
@@ -41,6 +41,7 @@ class LocalStorageAuthStore {
 function prepareSlug(slug) {
   return (
     slug
+      .trim()
```
Comment (erquhart) [inline packages/netlify-cms-core/src/backend.js]: Preview link paths have their individual segments passed through this function, but slug templates go through this function whole, so it seems possible that this could result in untrimmed segments within the slug. Perhaps removing all whitespace from the slug after processing as a precaution could work?

Comment (barthc) [reply packages/netlify-cms-core/src/backend.js]: @erquhart  did a little bit of testing and I think we don't really need to `trim` each segment of the slug here. Turns out that the  urlHelper `sanitizeURI` turns  all white space to the config's `sanitize_replacement` option and then the `(double|trailing|leading)Replacement` does the final work, thoughts.

Comment (erquhart) [reply packages/netlify-cms-core/src/backend.js]: Alright, sounds like we're covered - thanks for digging into that 👍
