### PR TITLE
Don’t try to validate an optional field if it is empty

### LINKED ISSUE #1175: Don’t try to validate an optional field if it is empty
- **Bug report**

- **What is the current behavior?**
  If a field has a `pattern` option to validate input _and_ a `required` option set to `false`, Netlify CMS initially tries to validate the empty field and rejects it. If the `pattern` accounts for an empty string — e.g. `^(pattern)?$` — this will only validate once a value has been input and then removed. I don’t know, but I assume this is perhaps because the initial validation tries to run the `RegEx` on `undefined` and only after input runs it against an empty string.

- **If the current behavior is a bug, please provide the steps to reproduce.**

  1. Create a field with the following parameters (for example):
      ```yml
      - name: url
        label: URL
        pattern: ['^(https?:\/\/.+)?$', 'Must start with http:// or https://']
        widget: string
        required: false
      ```

  2. Create a new post, leave the `url` field blank, and try to save the post. The `url` field should flag as invalid.

  3. Enter some text into the `url` field and then delete it. Try to save the post. The `url` field should now validate.

- **What is the expected behavior?**
  If a field is marked as optional (i.e. `required: false`), validation should not be run if the field is `undefined`, `null`, or an empty string.

- **Please mention your CMS, node.js, and operating system version.**
  - Netlify CMS: 1.3.5
  - Node: not applicable
  - OS: OS X 10.9.5, using Chrome 64.0.3282.186

### PR DESCRIPTION
**Pull request by Dammmien**
**- Summary**

Fixes #1175 : Don’t try to validate an optional field if it is empty

**- Test plan**

If a field is marked as optional (i.e. required: false), validation should not be run if the field is undefined, null, or an empty string.

**- Description for the changelog**

Don’t try to validate an optional field if it is empty

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit a4486dd4963d9e334d943b744065a140b9b28100

https://deploy-preview-1237--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit a4486dd4963d9e334d943b744065a140b9b28100

https://deploy-preview-1237--netlify-cms-www.netlify.com

File: src/components/Editor/EditorControlPane/Widget.js [hunk 1]
```diff
@@ -104,7 +104,9 @@ export default class Widget extends Component {
 
   validatePattern(field, value) {
     const pattern = field.get('pattern', false);
-    if (pattern && !RegExp(pattern.first()).test(value)) {
+    const hasValue = typeof value === 'string' && value.length > 0;
```
Comment (erquhart) [inline src/components/Editor/EditorControlPane/Widget.js]: This would stop non-string fields (e.g. numbers) from being pattern validated.

Instead of adding logic, you could split out the empty field test logic from `validatePresence` and reuse it here.

**Comment by Dammmien** [comment]
@erquhart I split out the empty field test logic and use it in the two validation functions.

File: src/components/Editor/EditorControlPane/Widget.js [hunk 2]
```diff
@@ -84,14 +91,9 @@ export default class Widget extends Component {
     this.props.onValidate(errors);
   };
 
-  validatePresence(field, value) {
+  validatePresence = (field, value) => {
```
Comment (erquhart) [inline src/components/Editor/EditorControlPane/Widget.js]: Not certain we want to convert these to lexically scoped (fat arrow) functions, let's leave it as is to be safe. This applies to `validatePattern` as well.

File: src/components/Editor/EditorControlPane/Widget.js [hunk 3]
```diff
@@ -67,6 +67,13 @@ export default class Widget extends Component {
     this.wrappedControlShouldComponentUpdate = scu && scu.bind(wrappedControl);
   };
 
+  isEmpty = (value) => (
```
Comment (erquhart) [inline src/components/Editor/EditorControlPane/Widget.js]: Let's move this out into a standalone function beneath `truthy`.

File: src/components/Editor/EditorControlPane/Widget.js [hunk 4]
```diff
@@ -100,10 +102,13 @@ export default class Widget extends Component {
...
     }
     return { error: false };
-  }
+  };
 
-  validatePattern(field, value) {
+  validatePattern = (field, value) => {
     const pattern = field.get('pattern', false);
+
+    if (this.isEmpty(value)) return { error: false };
```
Comment (erquhart) [inline src/components/Editor/EditorControlPane/Widget.js]: Avoid single line if statements, especially when they return.

**Comment by Dammmien** [comment]
Done @erquhart !

**Comment by Dammmien** [comment]
@erquhart , @tech4him1 something is blocking to merge ?

**Comment by erquhart** [comment]
We try to get two maintainer approvals before merging, that's all. 

@tech4him1 @talves @benaiah thoughts?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
