### PR TITLE
fix(backend-git-gateway): omit /repos/ when no repo

### LINKED ISSUE #2844: Loading entries does not work with Github backend
**Describe the bug**
I have an issue very similar to https://github.com/netlify/netlify-cms/issues/2629

After login I can see all my posts, clicking on one I get "Failed to load entry: Access to endpoint not allowed: this part of GitHub’s API has been restricted"

My network looks like:
netlifycms-error

**To Reproduce**
Here is my repo https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis and it's connected to https://vigorous-newton-f5373c.netlify.com/

**Expected behavior**

I can edit my existing posts.

**Applicable Versions:**

 - Netlify CMS version: 2.9.8-beta.4
 - Git provider: git-gateway
 - OS: MacOS
 - Browser version Chrome 78

 - Node.JS version: 12.11

**CMS configuration**
[https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis/blob/master/static/admin/config.yml](https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis/blob/master/static/admin/config.yml)

**Additional context**

### PR DESCRIPTION
**Pull request by erquhart**
Fixes #2844

### CODE REVIEW

**Comment by chrfritsch** [comment]
Thanks @erquhart for working on this. I applied this patch to https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis and it doesn't seem to fix the problem. I still see broken links in the network tab.

File: packages/netlify-cms-backend-github/src/API.js [hunk 1]
```diff
@@ -24,9 +24,9 @@ export default class API {
     this.useOpenAuthoring = config.useOpenAuthoring;
     this.repo = config.repo || '';
     this.originRepo = config.originRepo || this.repo;
-    this.repoURL = `/repos/${this.repo}`;
+    this.repoURL = this.repo ? `/repos/${this.repo}` : '';
```
Comment (erezrokah) [inline packages/netlify-cms-backend-github/src/API.js]: I think `repoURL` and `originRepoURL` will always be set to an empty string with `git-gateway` since `config.repo` is `undefined` as passed here: https://github.com/netlify/netlify-cms/blob/c1c95874f41bd2b435c39d3dea263c77eaa601eb/packages/netlify-cms-backend-git-gateway/src/implementation.js#L160.

Also the `repoURL` value is overwritten in the parent class when using `git-gateway` https://github.com/netlify/netlify-cms/blob/c1c95874f41bd2b435c39d3dea263c77eaa601eb/packages/netlify-cms-backend-git-gateway/src/GitHubAPI.js#L10

File: packages/netlify-cms-backend-github/src/API.js [hunk 2]
```diff
@@ -24,9 +24,9 @@ export default class API {
...
     // when not in 'useOpenAuthoring' mode originRepoURL === repoURL
-    this.originRepoURL = `/repos/${this.originRepo}`;
+    this.originRepoURL = this.originRepo ? `/repos/${this.originRepo}` : '';
```
Comment (erezrokah) [inline packages/netlify-cms-backend-github/src/API.js]: `repoURL` will always be an empty string for `git-gateway` as it is overwritten here: https://github.com/netlify/netlify-cms/blob/c1c95874f41bd2b435c39d3dea263c77eaa601eb/packages/netlify-cms-backend-git-gateway/src/GitHubAPI.js#L10

I think we should add the same for `originRepoURL` (I missed it in this fix https://github.com/netlify/netlify-cms/pull/2631)

Comment (erezrokah) [reply packages/netlify-cms-backend-github/src/API.js]: I think that's why it was partially working. `repoURL` was ok but `originRepoURL` not

**Comment by erezrokah** [comment]
Hey @chrfritsch, I managed to reproduce the issue locally and with @erquhart fix I could load the entries.
FYI, what I did was to deploy your repo to Netlify (enabled identity, git-gateway, etc.), switched to @erquhart branch, updated the `dev-test` site `config.yml` and `index.html` and tested without/with the fix.

**Comment by chrfritsch** [comment]
Hm ok. So maybe I did something wrong. It's the first time I use the patch-packages package. But at least in the build log, it says that the patch was applied. https://app.netlify.com/sites/vigorous-newton-f5373c/deploys/5dc25eb8bc854d00086443b0

**Comment by erezrokah** [comment]
I'm not sure how patch packages work. Does it update only the source file or also runs the build command? You'll need to make the patched files are built into `dist`.

**Comment by chrfritsch** [comment]
Ah I get it. Ok, I am trying to create another patch.

**Comment by chrfritsch** [comment]
I managed to create a proper patch and the issue is fixed. 👍

**Comment by chrfritsch** [comment]
Thank you. Now would be a good time to tag new release 😊

**Comment by erquhart** [comment]
This is released under `netlify-cms`/`netlify-cms-app` 2.9.8-beta.5
