### PR TITLE
Fix thumbs for new uploads to private repos

### LINKED ISSUE #993: Need to reload page after uploading image to show the thumbnail
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
When working on a private repo, new image uploads don't show the thumbnail until you reload the page, leading the user sometimes to think the upload failed because they see a broken thumbnail icon. Apparently the src url of new images don't have the `token` query parameter that is applied when the page loads, a page reload makes the thumbnail appear as expected.
screen shot 2018-01-08 at 14 39 03

**- If the current behavior is a bug, please provide the steps to reproduce.**
- Open media library
- Upload new image
- Wait for image to be uploaded so that its item shows before the others

**- What is the expected behavior?**
I'd expect the thumbnail to be visible immediately after upload is finished.

**- Please mention your CMS, node.js, and operating system version.**

Netlify CMS 1.0.3, also tried with latest master running on Node 8.9.3 (lts/carbon).

**- Please link or paste your `config.yml` below if applicable.**
```yaml
backend:
  name: github
  ...
media_folder: "/static/images/uploads"
public_folder: "/images/uploads"
```

### PR DESCRIPTION
**Pull request by Quicksaver**
Closes #993.

**- Summary**

When working on a private repo, new image uploads don't show the thumbnail until you reload the page, leading the user sometimes to think the upload failed because they see a broken thumbnail icon. The src url of new images don't have the token query parameter that is applied when the page loads.

This fix reloads the file list of the upload directory from the git API (as if it was first loading the media library), and fetches the url of the newly uploaded file from that list. I left the previous built-in-the-method url as a fallback, *just in case*.

**Note:** my fix seems the "simplest" in terms of what I could already find in the code, but if you think there's a better way to do it, I'm all up for it. 😄 

**- Test plan**

Tested uploading an image, to a private repository, through the media library. The thumbnail appeared immediately as expected. Also tested in a public repo, all fine as before as well.

**- Description for the changelog**

(Media Library) Fix broken thumbnail when uploading an image to a private repository

**- A picture of a cute animal (not mandatory but encouraged)**
img_20171126_123023

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit c5ffb189f2030bc6cef10004724582f1e17b8f63

https://deploy-preview-994--cms-demo.netlify.com

**Comment by tech4him1** [comment]
@Quicksaver Do the `download_url`s automatically have the tokens added to them?

**Comment by Quicksaver** [comment]
@tech4him1 it seems they do, they also come directly from the git API on load at least.

**Comment by Quicksaver** [comment]
PS not really sure why the build is failing, I can't tell locally as running lint on master also fails. Please let me know if there's something I can do on my end to fix that.

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit c5ffb189f2030bc6cef10004724582f1e17b8f63

https://deploy-preview-994--netlify-cms-www.netlify.com

**Comment by tech4him1** [comment]
@Quicksaver Looks like the build just had a connection issue, should be fixed now.

File: src/backends/github/implementation.js [hunk 1]
```diff
@@ -136,8 +136,18 @@ export default class GitHub {
       const response = await this.api.persistFiles(null, [mediaFile], options);
       const repo = this.repo || this.getRepoFromResponseUrl(response.url);
       const { value, size, path, fileObj } = mediaFile;
-      const url = `https://raw.githubusercontent.com/${repo}/${this.branch}${path}`;
-      return { id: response.sha, name: value, size: fileObj.size, url, path: trimStart(path, '/') };
+      let url = `https://raw.githubusercontent.com/${repo}/${this.branch}${path}`;
+
+      // Assets uploaded to private repos will need valid access tokens.
+      const files = await this.api.listFiles(this.config.get('media_folder'));
```
Comment (tech4him1) [inline src/backends/github/implementation.js]: I think we should only get the file that we are actually wanting, not the entire `media_folder` again. This could be accomplished by making a function essentially like `listFiles`, except for requesting a single file instead of a directory.

Comment (tech4him1) [reply src/backends/github/implementation.js]: Also, I do think double-checking the SHA here is a good idea, as we don't want to run into caching issues. When we were constructing the URL manually before, though, we definitely weren't worrying about caching.

Comment (Quicksaver) [reply src/backends/github/implementation.js]: @tech4him1

> I think we should only get the file that we are actually wanting

I wanted to do that, but I couldn't find any API in the docs that could be used for that. The [Contents API](https://developer.github.com/v3/repos/contents/#get-contents) being used now, if pointed at a file rather than at a directory, will also retrieve the contents of that file. So we'd be transferring the whole image file twice, once just to get the metadata containing its `download_url`, and again later on to show the thumbnail (as it's a different url so it's not cached).

That API also has a 1 Mb limit, so it won't work for larger files, we'd need the [Blobs API](https://developer.github.com/v3/git/blobs/#get-a-blob) to retrieve those files, but that doesn't include the `download_url`.

As far as I can tell, this really seems to be the most direct way to get the tokenized `download_url` currently used to show the thumbnails. Those alternatives are probably useful for #990 though.

Comment (erquhart) [reply src/backends/github/implementation.js]: The only other option I can think of is super hacky - parse the token from the download_url of another image. 99.9% sure we just shouldn't.

So that aside, we should:

1) only take the approach provided here for private repos
2) hurry up and get thumbnail creation in place (#946), and ensure thumbnails are well below 1mb, so we can stop doing this

**Comment by erquhart** [comment]
@Quicksaver this is better than nothing for private repos, we can still merge it if it's updated to only apply for those.

**Comment by Quicksaver** [comment]
@erquhart I've been wanting to do that but haven't had a chance to work on it at all since back then. 😭

**Comment by erquhart** [comment]
No problem! I'll leave it open for now in case you or someone else finds time to get it in.

**Comment by robertgonzales** [comment]
I'm seeing this issue, but not just for new uploads. No thumbnails load even with the token param.

**Comment by erquhart** [comment]
@robertgonzales that would qualify as a separate issue, can you open one with a repro case?

**Comment by Quicksaver** [comment]
@erquhart @tech4him1 re-fixed for private repositories only (finally!) 😄 I couldn't find anywhere else that was already checking if the repo is private, so I created a new method in the API script just for that, could be useful for other features down the line as well I guess.

File: src/backends/github/implementation.js [hunk 2]
```diff
@@ -137,8 +137,21 @@ export default class GitHub {
...
       const { value, size, path, fileObj } = mediaFile;
-      const url = `https://raw.githubusercontent.com/${repo}/${this.branch}${path}`;
-      return { id: response.sha, name: value, size: fileObj.size, url, path: trimStart(path, '/') };
+      let url = `https://raw.githubusercontent.com/${repo}/${this.branch}${path}`;
+
+      // Assets uploaded to private repos will need valid access tokens.
+      const isPrivateRepo = await this.api.isPrivateRepo();
+      if (isPrivateRepo) {
+        const files = await this.api.listFiles(this.config.get('media_folder'));
+        for (let file of files) {
```
Comment (tech4him1) [inline src/backends/github/implementation.js]: I think we could make this code a bit simpler by using `find()` instead of looping:
```js
const file = files.find(f => (f.sha === mediaFile.sha));
if (file) {
  url = file.download_url;
}
```

File: src/backends/github/API.js [hunk 3]
```diff
@@ -30,6 +30,15 @@ export default class API {
       });
   }
 
+  isPrivateRepo() {
+    return this.request(this.repoURL)
+      .then(repo => repo.private)
+      .catch(error => {
```
Comment (tech4him1) [inline src/backends/github/API.js]: `request()` should catch itself on an API error -- we probably don't need to catch here unless there is a good reason.

Comment (Quicksaver) [reply src/backends/github/API.js]: I copied this from the `hasWriteAccess()` method above. Without knowing more about why that one is written like that, I couldn't tell you if it needs the catch or not, although yeah `request()` should probably catch it by itself. What do you think, should I keep it or remove it?

Comment (tech4him1) [reply src/backends/github/API.js]: Let's go ahead and remove it, Benaiah agreed as well.

**Comment by Quicksaver** [comment]
@tech4him1 removed the `catch()`.

**Comment by Quicksaver** [comment]
@tech4him1 and changed the loop into a `.find()` as well (almost forgot to mention).

File: src/backends/github/implementation.js [hunk 4]
```diff
@@ -137,8 +137,19 @@ export default class GitHub {
...
+      if (isPrivateRepo) {
+        const files = await this.api.listFiles(this.config.get('media_folder'));
+        const file = files.find(f => (f.sha === mediaFile.sha));
+        if (file) {
+          url = file.download_url;
+        }
+      }
+
+      return { id: mediaFile.sha, name: value, size: fileObj.size, url, path: trimStart(path, '/') };
     }
```
Comment (tech4him1) [inline src/backends/github/implementation.js]: It looks like we're returning the file SHA now, instead of the response (commit) SHA. Maybe I just missed the reason for this, can you explain? :smile:

Comment (Quicksaver) [reply src/backends/github/implementation.js]: @tech4him1 `response.sha` is undefined (yep, it was setting an undefined id before), at most it would have been `response.object.sha`. I set it to the file's sha instead to be more consistent with the other ids from when the media library initializes: https://github.com/netlify/netlify-cms/blob/master/src/backends/github/implementation.js#L94-L104

It's not really part of the original issue, true. But I thought since I was already in that very same line of code, I'd throw that in. 😅

Comment (tech4him1) [reply src/backends/github/implementation.js]: @Quicksaver Sounds good, maybe it should be split into a seperate commit? (same PR is fine)

Comment (Quicksaver) [reply src/backends/github/implementation.js]: @tech4him1 makes sense, I split it into a separate commit. Also, I just stumbled upon a redundant file.filter call in `getMedia()` in implementation.js (`listFiles()` in API.js already has an exact same one) so I went ahead and created a commit for it as well. Let me know if I'm filling this PR too much with non-relevant commits. 😁

**Comment by Quicksaver** [comment]
@tech4him1 Also, I just stumbled upon a redundant file.filter call in `getMedia()` in *implementation.js* (`listFiles()` in *API.js* already has an exact same one) so I went ahead and created a commit for it as well. Let me know if I'm filling this PR too much with non-relevant commits. 😁

**Comment by tech4him1** [comment]
@Quicksaver Thank you! I think that the `filter` change should be in a seperate PR, since it's not really related. It's up to you on the `sha` one, it could be lumped with either one, or seperate.

**Comment by buzzlightyear182** [comment]
Hello! I'm following the Quick Start Guide from the site so I'm using v 1.0.0 (https://unpkg.com/netlify-cms@^1.0.0) and I have the same issue with uploading images and thumbnails. I saw the PR was merged, but I'm not really sure how that works, is it there already in CDN?

**Comment by tech4him1** [comment]
@buzzlightyear182 Make sure you have the caret in the link `^1.0.0`, so that it automatically upgrades to the latest CMS version (v1.4.0). You can also try `^1.4.0` (still with the caret) to force the version. If you are are still having the problem, you can file a new issue with steps to reproduce.
