### PR TITLE
#895 Adding an image to an empty rich text editor doesn't trigger the Image widget

### LINKED ISSUE #895: Adding an image to an empty rich text editor doesn't trigger the Image widget
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**

add-image-bug

**- If the current behavior is a bug, please provide the steps to reproduce.**

- Create a new post that has a rich text field
- Click on the editor, then click on the + button and select "Image" from the dropdown
- The image widget appears for a second and disappears, leaving the text `null` 
 
**- What is the expected behavior?**
- The image widget doesn't disappear.

**- Please mention your CMS, node.js, and operating system version.**

Netlify CMS version 1.0.0, Chrome Version 62.0.3202.94 (Official Build) (64-bit), Mac OS Sierra

### PR DESCRIPTION
**Pull request by Dammmien**
Fixes #895 : Adding an image to an empty rich text editor doesn't trigger the Image widget.

**- Summary**

- Improve RegExp
- Do not fallback undefined alt to an empty string.
  Input will be filled with `undefined` label ( the youtube widget has this behavior ).

**- Test plan**

Add an image to an empty rich text editor

**- Description for the changelog**

- Improve RegExp
- Do not fallback undefined alt to an empty string
  Input will be filled with `undefined` label ( the youtube widget has this behavior ).

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 61f2a10e6b49e054d5dcc2731aa11eb116424bed

https://deploy-preview-926--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 61f2a10e6b49e054d5dcc2731aa11eb116424bed

https://deploy-preview-926--cms-demo.netlify.com

File: src/components/MarkdownPlugins/image.js [hunk 1]
```diff
@@ -7,9 +7,9 @@ const image = {
     image: match[2],
     alt: match[1],
   },
-  toBlock: data => `![${ data.alt || '' }](${ data.image || '' })`,
+  toBlock: data => `![${ data.alt }](${ data.image || '' })`,
   toPreview: (data, getAsset) => <img src={getAsset(data.image || '')} alt={data.alt || ''} />,
```
Comment (tech4him1) [inline src/components/MarkdownPlugins/image.js]: @erquhart I noticed that you modified this line as well in your 1.0 changes -- I had it as `src={getAsset(data.image) || ''}`.

Comment (erquhart) [reply src/components/MarkdownPlugins/image.js]: @tech4him1 good catch, yes, that was unintentional.

File: src/components/MarkdownPlugins/image.js [hunk 2]
```diff
@@ -7,9 +7,9 @@ const image = {
     image: match[2],
     alt: match[1],
   },
-  toBlock: data => `![${ data.alt || '' }](${ data.image || '' })`,
```
Comment (tech4him1) [inline src/components/MarkdownPlugins/image.js]: @Dammmien I'm just wondering why we want it to be `undefined` instead of an empty string, since that was just implemented recently. I'm not saying it's wrong, I'd just like a little background on why you can to change it.

Comment (erquhart) [reply src/components/MarkdownPlugins/image.js]: I think his reasoning lies in comparison to the youtube component:
