### PR TITLE
Check user permissions and metadata every CMS load.

### LINKED ISSUE #556: Check user write access even with remembered credentials
**- Do you want to request a *feature* or report a *bug*?**
bug, related to #491 and somewhat related to #539

**- What is the current behavior?**
When a user logs in, their OAuth access token and user information is saved so that they do not need to re-login on browser refresh. We also check and make sure that they have permission to access the repository, and fail if they do not have permission. When we re-hydrate that saved user info, however, we do not check permissions again, which means that if the `config.yml` was changed to a different repo, or the user's repo permissions were downgraded. Another side effect is that none of the user's info is refreshed (avatar, etc.)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Set up the CMS for a repo for which you have write permissions.
2. Log in to the CMS.
3. Change the `config.yml` repo to a repo for which you do not have write permissions.
4. Re-open the CMS. You will be logged in, but not able to save anything.

**- What is the expected behavior?**
The user's permissions should be checked and their info (avatar, etc.) updated *every load* of the CMS.

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**
Fixes #556.
Before, if the CMS was loading user OAuth credentials from `localStorage`, then user write access would not be checked again. However, the `config.yml` repo could be changed, which would cause the user to be still logged in even if they did not have write permissions. Also, if the user had updated their metadata (avatar, etc.), the CMS would not update that either.

The main change that this PR makes is that it expects `setUser` to return a rehydrated user object, instead of just taking the user object that it was fed and using it.

**- Test plan**

- [x] GitHub backend
- [x] `test-repo` backend
- [x] `git-gateway` backend

**- Description for the changelog**

Check user permissions and metadata *every* CMS load.

### CODE REVIEW

File: src/backends/netlify-auth/implementation.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ export default class NetlifyAuth extends GitHubBackend {
     AuthenticationPage.authClient = this.authClient;
   }
 
-  setUser() {
+  restoreUser() {
     const user = this.authClient.currentUser();
     if (!user) return Promise.reject();
     return this.authenticate(user);
```
Comment (tech4him1) [inline src/backends/netlify-auth/implementation.js]: Note: The result of what this function used to return was the `stored` value, now it would be the `this.authenticate` return value. I think this is what was originally intended, but not actually done, can someone else verify?

**Comment by tech4him1** [comment]
This also needs fixed in the case that the backend gets switched and the CMS is reloaded. @Benaiah what do you think about just saving the backend value into `localStorage` as part of the user value, then the CMS checks if it is the right user for the backend being used?

File: src/backends/git-gateway/implementation.js [hunk 2]
```diff
@@ -43,7 +43,7 @@ export default class GitGateway extends GitHubBackend {
     AuthenticationPage.authClient = this.authClient;
   }
 
-  setUser() {
+  restoreUser() {
     const user = this.authClient && this.authClient.currentUser();
     if (!user) return Promise.reject();
     return this.authenticate(user);
```
Comment (tech4him1) [inline src/backends/git-gateway/implementation.js]: The result of what this function used to return was the localStorage `stored` value, now it would be the `this.authenticate` return value. I think this is what was originally intended, but not actually done, can someone else verify?

File: src/backends/backend.js [hunk 3]
```diff
@@ -70,8 +71,11 @@ class Backend {
   currentUser() {
     if (this.user) { return this.user; }
     const stored = this.authStore && this.authStore.retrieve();
-    if (stored) {
-      return Promise.resolve(this.implementation.setUser(stored)).then(() => stored);
+    if (stored && (stored.backend === this.backendName)) {
+      return this.implementation.restoreUser(stored).then((user) => {
```
Comment (tech4him1) [inline src/backends/backend.js]: @Benaiah @erquhart What do you think is the best way to do this (especially for the `git-gateway` backend)? Completely remove the `restoreUser` function and send the stored user to `authenticate`, or keep it and just forward the calls for most backends like I did here?

File: src/backends/backend.js [hunk 4]
```diff
@@ -71,7 +71,10 @@ class Backend {
     if (this.user) { return this.user; }
     const stored = this.authStore && this.authStore.retrieve();
     if (stored) {
-      return Promise.resolve(this.implementation.setUser(stored)).then(() => stored);
+      return this.implementation.setUser(stored).then((user) => {
+        this.authStore.store(user);
```
Comment (erquhart) [inline src/backends/backend.js]: Since `this.authStore` defaults to `null`, we should check for existence first.

File: src/backends/backend.js [hunk 5]
```diff
@@ -70,10 +71,11 @@ class Backend {
   currentUser() {
     if (this.user) { return this.user; }
     const stored = this.authStore && this.authStore.retrieve();
-    if (stored) {
+    if (stored && (stored.backend === this.backendName)) {
```
Comment (erquhart) [inline src/backends/backend.js]: No parens necessary on the equality check. Also, keep the naming synced - if it's `this.backendName`, let's call it `backendName` in the stored user.

File: src/backends/backend.js [hunk 6]
```diff
@@ -70,10 +71,11 @@ class Backend {
...
       return this.implementation.setUser(stored).then((user) => {
-        this.authStore.store(user);
-        return user;
+        // return confirmed/new user object instead of stored
+        this.authStore.store({...user, backend: this.backendName});
+        return {...user, backend: this.backendName};
```
Comment (erquhart) [inline src/backends/backend.js]: Nitpick: maybe store this object you're creating twice in a `newUser` constant.

File: src/backends/backend.js [hunk 7]
```diff
@@ -85,8 +87,8 @@ class Backend {
 
   authenticate(credentials) {
     return this.implementation.authenticate(credentials).then((user) => {
-      if (this.authStore) { this.authStore.store(user); }
-      return user;
+      if (this.authStore) { this.authStore.store({...user, backend: this.backendName}); }
+      return {...user, backend: this.backendName};
```
Comment (erquhart) [inline src/backends/backend.js]: Same here, declare once, reference twice.

File: src/backends/backend.js (hunk 3 above)
Comment (erquhart) [reply src/backends/backend.js]: Removing the `restoreUser` function would mean users always have to log back in, no?

File: src/backends/backend.js [hunk 8]
```diff
@@ -70,8 +71,12 @@ class Backend {
   currentUser() {
     if (this.user) { return this.user; }
     const stored = this.authStore && this.authStore.retrieve();
-    if (stored) {
-      return Promise.resolve(this.implementation.setUser(stored)).then(() => stored);
+    if (stored && (stored.backend === this.backendName)) {
+      return this.implementation.restoreUser(stored).then((user) => {
+        // return confirmed/new user object instead of stored
+        this.authStore.store({...user, backend: this.backendName});
```
Comment (erquhart) [inline src/backends/backend.js]: Since `this.authStore` defaults to null, we should check for existence first.

File: src/backends/backend.js [hunk 9]
```diff
@@ -70,8 +71,12 @@ class Backend {
   currentUser() {
     if (this.user) { return this.user; }
     const stored = this.authStore && this.authStore.retrieve();
-    if (stored) {
-      return Promise.resolve(this.implementation.setUser(stored)).then(() => stored);
+    if (stored && (stored.backend === this.backendName)) {
```
Comment (erquhart) [inline src/backends/backend.js]: No parens necessary on the equality check. Also, keep the naming synced - if it's `this.backendName`, let's call it `backendName` in the stored user.

File: src/backends/backend.js [hunk 10]
```diff
@@ -70,8 +71,12 @@ class Backend {
...
+      return this.implementation.restoreUser(stored).then((user) => {
+        // return confirmed/new user object instead of stored
+        this.authStore.store({...user, backend: this.backendName});
+        return {...user, backend: this.backendName};
```
Comment (erquhart) [inline src/backends/backend.js]: Nitpick: maybe store this object you're creating twice in a `newUser` constant.

File: src/backends/backend.js [hunk 11]
```diff
@@ -82,8 +87,8 @@ class Backend {
 
   authenticate(credentials) {
     return this.implementation.authenticate(credentials).then((user) => {
-      if (this.authStore) { this.authStore.store(user); }
-      return user;
+      if (this.authStore) { this.authStore.store({...user, backend: this.backendName}); }
+      return {...user, backend: this.backendName};
```
Comment (erquhart) [inline src/backends/backend.js]: Same here, declare once, reference twice.

File: src/backends/git-gateway/implementation.js (hunk 2 above)
Comment (erquhart) [reply src/backends/git-gateway/implementation.js]: Originally we weren't doing anything with the return value at all (only called that one time in `src/backends/backends.js`), so no worries there.

File: src/backends/backend.js [hunk 12]
```diff
@@ -70,8 +71,12 @@ class Backend {
   currentUser() {
     if (this.user) { return this.user; }
     const stored = this.authStore && this.authStore.retrieve();
-    if (stored) {
-      return Promise.resolve(this.implementation.setUser(stored)).then(() => stored);
```
Comment (tech4him1) [inline src/backends/backend.js]: Oops, messed this up when rebasing.

File: src/backends/backend.js (hunk 3 above)
Comment (Benaiah) [reply src/backends/backend.js]: If removing `restoreUser` requires the user to log back in again anyway I'd say definitely leave this as is. Defining `restoreUser` as a call to `authenticate` in the backend seems like a perfectly fine way to handle backends that can't do any other restoration.

Comment (tech4him1) [reply src/backends/backend.js]: Good, I'll leave it like it is, then.

File: src/backends/git-gateway/implementation.js (hunk 2 above)
Comment (tech4him1) [reply src/backends/git-gateway/implementation.js]: @erquhart The difference was that before, the value stored in localStorage was returned, whereas now, the return value of this function is returned as the user.

File: src/backends/backend.js (hunk 3 above)
Comment (tech4him1) [reply src/backends/backend.js]: @erquhart No, I was mostly talking about the forwarding part of it, which @Benaiah addressed.

File: src/backends/backend.js (hunk 8 above)
Comment (tech4him1) [reply src/backends/backend.js]: @erquhart The reason I left that check off here is because we already know `this.authStore` exists -- it had to to get a `stored` value.

**Comment by tech4him1** [comment]
@erquhart @Benaiah changes should be addressed or explained. Also, I'm not sure if I explained it adequately -- the main change that this PR makes is that it expects `setUser` to return a rehydrated user object, instead of just taking the user object that it was fed and using it.

File: src/backends/backend.js (hunk 9 above)
Comment (tech4him1) [reply src/backends/backend.js]: Done.

File: src/backends/backend.js (hunk 10 above)
Comment (tech4him1) [reply src/backends/backend.js]: Done.

File: src/backends/backend.js (hunk 8 above)
Comment (tech4him1) [reply src/backends/backend.js]: Do you think it still needs checked?

File: src/backends/backend.js (hunk 11 above)
Comment (tech4him1) [reply src/backends/backend.js]: Done.

File: src/backends/backend.js (hunk 12 above)
Comment (tech4him1) [reply src/backends/backend.js]: Fixed.

File: src/backends/git-gateway/implementation.js (hunk 2 above)
Comment (tech4him1) [reply src/backends/git-gateway/implementation.js]: See https://github.com/netlify/netlify-cms/pull/559#issuecomment-334976455

Comment (erquhart) [reply src/backends/git-gateway/implementation.js]: Right - but it didn't matter what was returned before because we weren't using that return value anywhere. That means there should be no backwards compatibility considerations.

Comment (tech4him1) [reply src/backends/git-gateway/implementation.js]: I'm talking about this line: https://github.com/netlify/netlify-cms/blob/master/src/backends/backend.js#L81. You can see there that we are returning the `stored` user object. VS now, at https://github.com/netlify/netlify-cms/blob/remembered-credentials-check/src/backends/backend.js#L86 we are actually returning the output of `restoreUser`.

Comment (erquhart) [reply src/backends/git-gateway/implementation.js]: Ah, the return value of `currentUser` - I can't see why that would be an issue.
