### PR TITLE
fix list item deletion

### LINKED ISSUE #381: Fix list widget deletion
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

Regression from #359. Items in list widgets can't be deleted if they do not have metadata.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Run this project locally via `yarn start`.
2. Make sure `example/config.yml` hasn't been edited.
3. Visit localhost:8080
4. Click Settings in the left sidebar
5. Click Authors
6. Attempt to delete one of the author list items

**- What is the expected behavior?**

List items should be removable.

### PR DESCRIPTION
**Pull request by erquhart**
**- Summary**

Fixes #381 

List items without metadata could not be deleted, regression from #359.

**- Test plan**

Attempting to delete list entries without metadata now works. This was tested in the example project locally.

**- Description for the changelog**

Fix list item deletion

### CODE REVIEW

File: src/components/Widgets/ListControl.js [hunk 1]
```diff
@@ -102,8 +102,8 @@ export default class ListControl extends Component {
     return (e) => {
       e.preventDefault();
       const { value, metadata, onChange, forID } = this.props;
-      const parsedMetadata = { [forID]: metadata.removeIn(value.get(index).valueSeq()) };
-      onChange(value.remove(index), parsedMetadata);
+      const parsedMetadata = metadata && { [forID]: metadata.removeIn(value.get(index).valueSeq()) };
+      onChange(value.remove(index), parsedMetadata || undefined);
```
Comment (calavera) [inline src/components/Widgets/ListControl.js]: is that `|| undefined` really necessary? `parsedMetadata` will be null if there is no metadata, the onChange callback should know how to handle that, shouldn't it?

Comment (erquhart) [inline src/components/Widgets/ListControl.js]: Our lack of testing is biting us so much that I'm pretty strongly against changing contracts anywhere unnecessarily. That said, now that I look at it, `parsedMetadata` would actually be undefined in this case, so we can definitely remove it.
