### PR TITLE
#359 - Handle metadata for all children of a list field

### LINKED ISSUE #359: Only partial relation metadata available on list previews
**- Do you want to request a *feature* or report a *bug*?**
* BUG

**- What is the current behavior?**
* When adding a field with the `relation` widget to a `list`, the metadata available (see https://github.com/netlify/netlify-cms/blame/7aa77baea9e64aaaf3f1a610543263426dc661b4/docs/customization.md#L181) from the list field is not complete, the only metadata available at any given time refers to the last child updated.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Add a "collection1" with a field that can be referenced and some content in its directory.
2. Add a "collection2" with a `list` field, whose children refer to "collection 1" through `relation`, like:
```
- label: "People"
        name: "people"
        widget: "list"
        fields:
          - label: "Person"
            name: "person"
            widget: "relation"
            collection: "collection1"
            searchFields:
              - "title"
            valueField: "title"
```
3. Add a custom preview class through `CMS.registerPreviewTemplate` for "collection2" and monitor the values of `this.props.fieldsMetadata.get('people')` - there is only 1 entry, the last child edited on the `list` field.

**- What is the expected behavior?**
* On step 3 above, that metadata for every child of the `list` field is available, i.e., that for every item in `this.props.entry.getIn(['data', fieldName])` there is a corresponding item in `this.props.fieldsMetadata.get('fieldName')` filled with metadata.

**- Please mention your node.js, and operating system version.**
v6.9.5 on OS X 10.11.6

### PR DESCRIPTION
**Pull request by lmcorreia**
**- Summary**
* Closes #359 

**- Test plan**
* I know, no excuses for not writing any tests but I ended up having to test it all manually anyway in my use case. Adding, removing and updating any child of the `list` works, there are no incompatibilities with the current version, nothing needs to be changed in the docs (they don't go very deep into the `relation` widget anyway - room for improvement in another contribution), now works as expected. If you did the setup to confirm the bug exists (see #359), just adding, editing and removing entries in the list field should be enough to confirm that the metadata now comes as expected.

**- Description for the changelog**
* Handle metadata for all children of a list field

**- A picture of a cute animal (not mandatory but encouraged)**
wiki

### CODE REVIEW

**Comment by lmcorreia** [comment]
Sorry, just noticed a little screw up in the diff from screwing around with values, fixing it

**Comment by lmcorreia** [comment]
^ Now we're good :)

File: src/components/Widgets/ListControl.js [hunk 1]
```diff
@@ -193,3 +197,7 @@ export default class ListControl extends Component {
     />);
   }
 }
+
+
+// WEBPACK FOOTER //
+// ./components/Widgets/ListControl.js
```
Comment (Benaiah) [inline src/components/Widgets/ListControl.js]: Looks like these lines were left in inadvertently.

**Comment by josephearl** [comment]
@Benaiah @lmcorreia webpack footer removed

**Comment by josephearl** [comment]
LGTM

**Comment by lmcorreia** [comment]
Sorry, must have been my build settings. Thanks for the commit, @josephearl
