### PR TITLE
Fix broken new media uploads in Git Gateway.

### LINKED ISSUE #1220: Regression: Image card with thumbnails not showing after upload
**- Do you want to request a *feature* or report a *bug*?**
Report a bug

**- What is the current behavior?**
When I upload an image, page needs to be reloaded in order for image block to appear. I can see the photo is uploaded when the button changes back to "Upload New". Deleting an image works fine as expected. Attached is a screenshot of the errors in console. Not sure why API.js is unauthorized as I can login and publish articles already.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Code is hosted on a public repo. I used `<script src="https://unpkg.com/netlify-cms@^1.4.0/dist/cms.js"></script>` and `<link rel="stylesheet" href="https://unpkg.com/netlify-cms@^1.4.0/dist/cms.css" />` in admin/index.html
Upload image in Media

**- What is the expected behavior?**
When image is uploaded, thumbnail and file name should appear once done.

**- Please mention your CMS, node.js, and operating system version.**

Netlify v1.4.0

**- Please link or paste your `config.yml` below if applicable.**
screen shot 2018-04-01 at 3 10 31 pm

config.yml
``` 
backend:
  name: git-gateway
  branch: master # Branch to update (master by default)
  
media_folder: "source/blog/images" # Folder where user uploaded files should go
public_folder: "/blog/images" # CMS now knows 'source' is the public folder and will strip this from the path

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Create News Article" # Used in the UI, ie.: "New Post"
    folder: "source/blog/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Category", name: "category", widget: "hidden", default: "news"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Featured Image", name: "cover_image", widget: "image"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Summary", name: "metadescription", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "learning-zone" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Create Learning Zone Article" # Used in the UI, ie.: "New Post"
    folder: "source/blog/learning-zone" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Category", name: "category", widget: "hidden", default: "learning-zone"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Featured Image", name: "cover_image", widget: "image"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
```

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

New media uploads do not appear at all until the CMS is reloaded **(not the thumbnail or filename)** when using the Git Gateway backend after #994. This PR resolves #1220.

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: src/backends/github/implementation.js [hunk 1]
```diff
@@ -139,8 +139,10 @@ export default class GitHub {
       let url = `https://raw.githubusercontent.com/${repo}/${this.branch}${path}`;
 
       // Assets uploaded to private repos will need valid access tokens.
-      const isPrivateRepo = await this.api.isPrivateRepo();
-      if (isPrivateRepo) {
+      if (!this.isPrivateRepo) {
+        this.isPrivateRepo = await this.api.checkPrivateRepo(`${this.api_root}/repos/${repo}`);
```
Comment (tech4him1) [inline src/backends/github/implementation.js]: The value is cached here since GitHub limits unauthenticated API requests. The only downside is that you need to reload the CMS page if you change the repo from public to private.

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit c59926962abc394ac093d976d33a91bd135c9e58

https://deploy-preview-1221--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit c59926962abc394ac093d976d33a91bd135c9e58

https://deploy-preview-1221--netlify-cms-www.netlify.com

File: src/backends/git-gateway/API.js [hunk 2]
```diff
@@ -27,6 +27,12 @@ export default class API extends GithubAPI {
       });
   }
 
+  checkPrivateRepo(url) {
+    const cacheBuster = new Date().getTime();
+    return fetch(`${url}?ts=${cacheBuster}`)
+      .then(response => response.ok);
```
Comment (tech4him1) [inline src/backends/git-gateway/API.js]: It might be a good idea to check if we get a 403 (rate limited) error here, and assume that the repo is private in that case so that thumbnails don't break.

File: src/backends/github/implementation.js (hunk 1 above)
Comment (erquhart) [reply src/backends/github/implementation.js]: I think that's a fine compromise.

File: src/backends/git-gateway/API.js (hunk 2 above)
Comment (erquhart) [reply src/backends/git-gateway/API.js]: That makes sense.

File: src/backends/github/implementation.js [hunk 3]
```diff
@@ -139,8 +139,10 @@ export default class GitHub {
       let url = `https://raw.githubusercontent.com/${repo}/${this.branch}${path}`;
 
       // Assets uploaded to private repos will need valid access tokens.
-      const isPrivateRepo = await this.api.isPrivateRepo();
-      if (isPrivateRepo) {
+      if (!this.isPrivateRepo) {
```
Comment (erquhart) [inline src/backends/github/implementation.js]: This condition would result in an unauthenticated check on every persist for public repos, maybe we should check for the presence of a Boolean instead.

Comment (tech4him1) [reply src/backends/github/implementation.js]: @erquhart How do you suggest checking for a boolean? I'm caching this value in th line below so that it only gets called once per CMS session.

Comment (tech4him1) [reply src/backends/github/implementation.js]: Oops, thank you!

**Comment by tech4him1** [comment]
@erquhart Great, thank you.

**Comment by erquhart** [comment]
As bad of a solution as it is, it may be better to always treat Git Gateway repos as private until #990 is in place.

**Comment by tech4him1** [comment]
@erquhart I've created an alternative PR with that fix (#1223). Is that your preferred solution for now?

**Comment by tech4him1** [comment]
I've updated the PR to use the file contents directly (as a `blob` URL) when new media is uploaded. This prevents us from having to infer the GitHub URL. Once the CMS is reloaded, the GitHub URL will be fetched automatically. This is not dependent on deploys at all, since it depends on the repo directly, instead of the website.

It works perfectly for me using GitHub and Git-Gateway backends with a public repo. @erquhart Can you test private?
