### PR TITLE
Prevent login if Git Gateway is disabled.

### LINKED ISSUE #1272: Error: Unrecognized front-matter format. + TypeError: e.commit is undefined
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**- Do you want to request a *feature* or report a *bug*?**
Report a bug.

**- What is the current behavior?**
Nothing works. Maybe I'm just tired but I can't get Netlify to work and keep running into these 2 errors.

**- If the current behavior is a bug, please provide the steps to reproduce.**
- Start up a fresh Jekyll Project.
- Add the Netlify CMS code to the /admin folder (config.yml + index.html)
- add the required scripts to the default layout
- create a new repo with Github, launch the site with Netlify
- visit mywebsite.netlify.com/admin, log in

**- What is the expected behavior?**

I keep running into strange error console messages and 404 network errors. I can't post new pages, and I can't upload images. Basically, nothing works and I don't understand the errors the console has thrown at me.

Thinking I must have done a mistake setting up Netlify CMS, I cloned one of my previous projects (which is also using Netlify CMS, and everything is working fine) and deployed it using Netlify, with a temporary URL.

When I log in to this new, freshly cloned website, I get the same errors.. even though the code is identical as my currently working project.

I'm stumped, since the code and configuration are identical. Yet, on any freshly deployed Netlify websites, the Netlify CMS isn't working for me, at all.

I'm going to try adding a custom domain to these new instances, since that is the only difference I can think of between the new projects and the old, working one.

Please take a look at the included screenshots for the error messages.

**INFO:**

Netlify CMS version 1.5.0
Client-side Node: v8.11.0
Netlify-side Node: node v8.11.1 (npm v5.6.0)
OS: Fedora 26 (x86-64)

**- Please link or paste your `config.yml` below if applicable.**

(I don't think this is an issue with the config.yml, but here it is just in case I made an obvious mistake?)

```
backend:

  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img"

collections:

  - name: "special-pages"
    label: "Pages uniques"
    delete: false # Prevent users from deleting documents in this collection
    files:
      - name: "home"
        file: "index.md"
        label: "Éditer la page d'accueil"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Paragraphe d'introduction", name: "home_intro", widget: "markdown"}
          - {label: "Paragraphe pour matériel premier soins", name: "home_materiel", widget: "markdown"}
          - {label: "Lien vers matériel premier soins", name: "link_materiel", widget: "string"}
          - {label: "Paragraphe pour formations", name: "home_formations", widget: "markdown"}
          - {label: "Lien vers formations", name: "link_formations", widget: "string"}
```

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Fixes #1272.

If Git Gateway was disabled, we were still allowing the user to log in, which can cause them to lose their work when they cannot save it.

**- Test plan**

Manually tested with both scenarios: https://github.com/netlify/netlify-cms/issues/1272#issuecomment-383139642.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: src/backends/github/API.js [hunk 1]
```diff
@@ -78,7 +78,11 @@ export default class API {
       if (contentType && contentType.match(/json/)) {
         return this.parseJsonResponse(response);
       }
-      return response.text();
+      const text = response.text();
+      if (!response.ok) {
```
Comment (tech4him1) [inline src/backends/github/API.js]: @Benaiah Is there any problem internally if we reject on not-OK responses for all content-types? We do on JSON responses already (see `parseJsonResponse`).

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 2a58992eda2f13ec19822293b9dc35945750613d

https://deploy-preview-1295--cms-demo.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 2a58992eda2f13ec19822293b9dc35945750613d

https://deploy-preview-1295--netlify-cms-www.netlify.com

File: src/backends/github/API.js (hunk 1 above)
Comment (Benaiah) [reply src/backends/github/API.js]: @tech4him1 yeah - I actually thought it was supposed to be doing so already. If the caller is expecting a non-ok response it can catch the `APIError`.
