### PR TITLE
fix(widget-relation): set initial metadata value

### LINKED ISSUE #4177: Missing fieldMetadata content for multiple relation widget in preview
I cannot show the content of a multiple relation widget inside a custom preview, since the fieldMetadata prop doesn't contain the data anymore.

**To Reproduce**
1. Create a relation field on a collection type with multiple true, referencing another collection type (es. post authors)
2. Populate the related entry (es. create some authors)
3. Populate the relation widget referencing the entry (es. insert in blog post related authors)
4. Register a custom preview component for the entry with the relation field

**Expected behavior**
The props passed to the preview component should contain the data for the relation entities, nested inside the fieldMetadata prop. This should allow the preview component to display the entry like in production. The expected content is like in https://github.com/netlify/netlify-cms/issues/2434#issuecomment-510563966.

**Applicable Versions:**
 - netlify-cms-app version: 2.14.19
 - Git provider: GitHub
 - OS: Windows 8
 - Browser version: latest Chrome
 - Node.JS version: 12.16.1

**Additional context**
The bug doesn't appear in netlify-cms-app 2.14.18. By exclusion, in my investigation I think it was probably introduced in #4063.

### PR DESCRIPTION
**Pull request by barthc**
Closes #4177

### CODE REVIEW

File: packages/netlify-cms-widget-relation/src/RelationControl.js [hunk 1]
```diff
@@ -111,22 +115,18 @@ export default class RelationControl extends React.Component {
...
-              const hits = payload.response?.hits || [];
-              const options = this.parseHitOptions(hits);
-              metadata[v] = hits[0]?.data;
-              return { options, index };
-            },
-          );
-        }),
-      );
+      const searchFieldsArray = getSearchFieldArray(field.get('search_fields'));
+      const { payload } = await query(forID, collection, searchFieldsArray, '', file);
```
Comment (erezrokah) [inline packages/netlify-cms-widget-relation/src/RelationControl.js:119]: Thanks @barthc.
Not sending a limit here can cause performance issues when referencing a large collection/file.
However I can't see a way to handle both at the moment.

**Review by erezrokah — APPROVED** [review]
