### PR TITLE
Do not close entry page if it failed to save or delete.

### LINKED ISSUE #555: Entry Page continues trying to close if entry not saved
**- Do you want to request a *feature* or report a *bug*?**
bug

https://github.com/netlify/netlify-cms/blob/9c0b7262efe8198429d5a1928a1abe7948c27046/src/containers/EntryPage.js#L100

**- What is the current behavior?**
Currently, if the user tries to save an entry, but the backend has an error, the page still tries to redirect back to the dashboard. However, since the page is not saved yet, the user is presented with a popup: "Are you sure you want to leave this page?". If they click "OK", their content is lost. After the popup is closed (OK or Cancel), the red error notification show up: "Failed to persist entry: API_ERROR: ...".

**- If the current behavior is a bug, please provide the steps to reproduce.**
This error can be simulated by throwing an error in `persistFiles` (`return Promise.reject("error");`). Then try to create or edit an entry in the GUI/editor. Click the "Save" button.

**- What is the expected behavior?**
If an error is encountered when the entry is being persisted, the CMS should not try to navigate away from the page (and care should be taken to preserve the user's content).

### PR DESCRIPTION
**Pull request by tech4him1**
**- Summary**

Fixes #555:
> Currently, if the user tries to save an entry, but the backend has an error, the page still tries to redirect back to the dashboard. However, since the page is not saved yet, the user is presented with a popup: "Are you sure you want to leave this page?". If they click "OK", their content is lost. After the popup is closed (OK or Cancel), the red error notification show up: "Failed to persist entry: API_ERROR: ...".

**- Test plan**

Manually tested with the `test-repo` backend by returning a rejected promise from `persistEntry` and `deleteFile`.

**- Description for the changelog**

Do not close entry page if the entry failed to save or delete.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: src/containers/EntryPage.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ class EntryPage extends React.Component {
   handlePersistEntry = () => {
     const { persistEntry, collection } = this.props;
     setTimeout(() => {
-      persistEntry(collection).then(() => this.handleCloseEntry());
+      persistEntry(collection).then(() => this.handleCloseEntry()).catch(() => {/* Don't do anything, the error will be shown by the action. */});
```
Comment (Benaiah) [inline src/containers/EntryPage.js]: I think the error here should continue to propagate, rather than be caught by the empty `catch` block, unless there's a particular reason you caught this here.

File: src/containers/EntryPage.js [hunk 2]
```diff
@@ -110,7 +110,7 @@ class EntryPage extends React.Component {
     const { deleteEntry, entry, collection } = this.props;
     const slug = entry.get('slug');
     setTimeout(() => {
-      deleteEntry(collection, slug).then(() => this.handleCloseEntry());
+      deleteEntry(collection, slug).then(() => this.handleCloseEntry()).catch(() => {/* Don't do anything, the error will be shown by the action. */});
```
Comment (Benaiah) [inline src/containers/EntryPage.js]: I think the error here should continue to propagate, rather than be caught by the empty `catch` block, unless there's a particular reason you caught this here.

File: src/actions/entries.js [hunk 3]
```diff
@@ -288,7 +288,7 @@ export function persistEntry(collection) {
           kind: 'success',
           dismissAfter: 4000,
         }));
-        return dispatch(entryPersisted(collection, serializedEntry));
+        return Promise.resolve(dispatch(entryPersisted(collection, serializedEntry)));
```
Comment (Benaiah) [inline src/actions/entries.js]: I don't think the `Promise.resolve` here isn't doing anything - `dispatch(entryDeleted(...))` should already be returning a promise.

File: src/actions/entries.js [hunk 4]
```diff
@@ -297,7 +297,7 @@ export function persistEntry(collection) {
           kind: 'danger',
           dismissAfter: 8000,
         }));
-        return dispatch(entryPersistFail(collection, serializedEntry, error));
+        return Promise.reject(dispatch(entryPersistFail(collection, serializedEntry, error)));
```
Comment (Benaiah) [inline src/actions/entries.js]: 👍

File: src/actions/entries.js [hunk 5]
```diff
@@ -310,7 +310,7 @@ export function deleteEntry(collection, slug) {
     dispatch(entryDeleting(collection, slug));
     return backend.deleteEntry(state.config, collection, slug)
     .then(() => {
-      return dispatch(entryDeleted(collection, slug));
+      return Promise.resolve(dispatch(entryDeleted(collection, slug)));
```
Comment (Benaiah) [inline src/actions/entries.js]: I don't think the `Promise.resolve` here isn't doing anything - `dispatch(entryDeleted(...))` should already be returning a promise.

File: src/actions/entries.js [hunk 6]
```diff
@@ -319,7 +319,7 @@ export function deleteEntry(collection, slug) {
         dismissAfter: 8000,
       }));
       console.error(error);
-      return dispatch(entryDeleteFail(collection, slug, error));
+      return Promise.reject(dispatch(entryDeleteFail(collection, slug, error)));
```
Comment (Benaiah) [inline src/actions/entries.js]: :+1:

File: src/actions/entries.js (hunk 3 above)
Comment (tech4him1) [reply src/actions/entries.js]: Good point -- since its returning from a `then`, it already gets wrapped in a promise.

File: src/containers/EntryPage.js (hunk 1 above)
Comment (tech4him1) [reply src/containers/EntryPage.js]: The only reason I did this was that I figured since the action is already showing a notification, we didn't need to do anything. I'll go ahead and test it without the `.catch` and make sure that there are no side effects, then I can remove it.

Comment (tech4him1) [reply src/containers/EntryPage.js]: Looks like the only "downside" is that you get duplicate error messages in the console, so I'll go ahead and remove this.

**Comment by tech4him1** [comment]
@Benaiah Should be updated now -- makes for a simple PR!
