### PR TITLE
Check for title/slug field on config load.

### LINKED ISSUE #690: save fails silently if no title field is configured
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
Saving fails silently if no title field is configured.

**- If the current behavior is a bug, please provide the steps to reproduce.**
- configure a collection with a single field called "test"
- enter text to the field
- save the entry
- observe error in console
- observe no error in UI

**- What is the expected behavior?**
There should be an error in the UI.

**- Please mention your CMS, node.js, and operating system version.**
CMS 0.5.1

### PR DESCRIPTION
**Pull request by tech4him1**
This PR fixes #690 by verifying that folder-type collections have a valid title ("slug"-able) field at CMS load time, instead of when the user tries to save an entry. It also explains how to fix the error.

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *netlify-cms-www* ready!

Built with commit 8b9afccc32b8a711e0ee1b7f9862d9d4d1cd7bad

https://deploy-preview-1203--netlify-cms-www.netlify.com

**Comment by verythorough** [comment]
Deploy preview for *cms-demo* ready!

Built with commit 8b9afccc32b8a711e0ee1b7f9862d9d4d1cd7bad

https://deploy-preview-1203--cms-demo.netlify.com

**Comment by erquhart** [comment]
Sweet! Is the WIP label still accurate?

**Comment by tech4him1** [comment]
@erquhart I haven't tested it much yet. Also, is this, in your opinion, too big of a change to the backend, or is it good to merge?

**Comment by erquhart** [comment]
It's mostly a refactor, just porting the identifier logic out to a selector, which makes sense, and improving the error message. I haven't given it a thorough review, but it seems merge ready to me.

**Comment by tech4him1** [comment]
This is going to need some more work before merge.

**Comment by tech4him1** [comment]
@erquhart I think I've fixed all the issues, but it probably deserves a pretty thorough review before merge -- the logic gets changed up quite a bit, it's not just a copy/paste.

**Comment by tech4him1** [comment]
Ready for review reminder 😆

**Comment by erquhart** [comment]
Alright I've got it queued.

File: src/reducers/collections.js [hunk 1]
```diff
@@ -51,8 +52,21 @@ function validateCollection(configCollection) {
...
     throw new Error(`Please set a proper frontmatter format for collection "${name}" to use a custom delimiter. Supported frontmatter formats are yaml-frontmatter, toml-frontmatter, and json-frontmatter.`);
   }
+  if ((!!folder) && (selectIdentifier(fields.map(f => f.name)) === undefined)) {
+    // Verify that folder-type collections have a "slug"-type field.
+    throw new Error(`Collection "${name}" must have a field that is a valid entry identifier. Supported fields are ${validIdentifierFields.join(',')}`);
+  }
 }
 
+const validIdentifierFields = ["title", "path"];
+export const selectIdentifier = (entryData) => {
```
Comment (erquhart) [inline src/reducers/collections.js]: `fieldNames` would be more self documenting than `entryData`, which I would expect to be a map of the actual entry data.

File: src/reducers/collections.js [hunk 2]
```diff
@@ -34,7 +34,8 @@ function validateCollection(configCollection) {
     files,
```
Comment (erquhart) [inline src/reducers/collections.js]: This `validateCollection` function is just validating configuration - I'd say move it to `Actions/config` with the rest of the config validation (all of which may be worth porting elsewhere in the future), which allows you to put the new selector in with the rest of the selectors under the `[FOLDER]` key.

**Comment by erquhart** [comment]
@tech4him1 mind reviewing this with my commit added on?

**Comment by tech4him1** [comment]
Will do.

**Comment by tech4him1** [comment]
@erquhart We'll throw every time here, instead of just when the `{{slug}}` placeholder is used. For example, we had people using only the date to save the file, without a title at all. Even though it is intended to always check, like this PR is doing, do you think it is a breaking change and we should merge into 2.0 instead?

**Comment by erquhart** [comment]
Yeah that makes sense - let's not backport this one if we can get away with it.

File: src/actions/config.js [hunk 3]
```diff
@@ -40,6 +43,38 @@ export function applyDefaults(config) {
...
+  }
+  if (!format && extension && !formatByExtension(extension)) {
+    // Cannot infer format from extension.
+    throw new Error(`Please set a format for collection "${name}". Supported formats are ${supportedFormats.join(',')}`);
+  }
+  if (delimiter && !frontmatterFormats.includes(format)) {
+    // Cannot set custom delimiter without explicit and proper frontmatter format declaration
+    throw new Error(`Please set a proper frontmatter format for collection "${name}" to use a custom delimiter. Supported frontmatter formats are yaml-frontmatter, toml-frontmatter, and json-frontmatter.`);
+  }
+  if (!!folder && !selectIdentifier(collection)) {
```
Comment (Benaiah) [inline src/actions/config.js]: I don't think the `!!` bool coercion here is necessary. Any value which would turn into `false` due to the coercion would also be ignored due to the `&&` which follows immediately after.

File: src/backends/backend.js [hunk 4]
```diff
@@ -41,23 +42,14 @@ class LocalStorageAuthStore {
...
-    const identifier = identifiers.find(ident => ident !== undefined);
-
-    if (identifier === undefined) {
-      throw new Error("Collection must have a field name that is a valid entry identifier");
-    }
-
-    return identifier;
-  };
+  const identifier = entryData.get(selectIdentifier(collection));
+  if (identifier === undefined) {
```
Comment (Benaiah) [inline src/backends/backend.js]: `if (identifier === undefined)` seems overly specific when `if (identifier)` seems to express the same semantics (none of `false`, `null`, and `0` are valid identifier field names either). If we'd rather avoid falsiness semantics, a better solution would be to use the second arguments to Immutable's `.get` and `.find` to explicitly return `false` when nothing is found.

Comment (tech4him1) [reply src/backends/backend.js]: This was just copying existing code, but if we're going for 2.0 this should be fine.
